### ISSUE TITLE
编程器电路提供器BUG

### ISSUE THREAD

**Issue by NNNNMMMMIIII** [reobf/Programmable-Hatches-Mod#10]
版本15p1
就是能放4个格子那个方块，如果里面放满东西然后用扳手拆了会丢失第3格的物品
比如里面放1 2 3 4电路板然后被扳手拆了就只掉1 2 4号电路板

**Comment by reobf** [comment]
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/v0.0.15p2-beta
修了
输入仓的判定被误用在提供器上了，导致第三格被认为是流体从而不掉落
就不改版本号了
