### ISSUE TITLE
smart blocking模式的bug

### ISSUE THREAD

**Issue by PinkYuDeer** [reobf/Programmable-Hatches-Mod#100]
版本：2.7.0 beta3 在二合一接口打开了阻挡模式和智能阻挡模式后，同一个配方的大批量的合成中，有概率会卡住。

具体表现为：液体进入缓存仓A，物品进入缓存仓B；一部分液体进入缓存仓A，物品和一部分液体进入缓存仓B。

**Comment by reobf** [comment]
从运行原理上不支持 不要开智能阻挡
缓存并不能识别 被倍增的输入，需要 物品/流体位置和数量完全一致

会乱可能是外缓容量不足，或者流体插入模式不合适，导致单次发配不完全

**Comment by PinkYuDeer** [comment]
拥有进阶缓存二合一接口在开启阻挡模式时、速度并不算太慢。是否本就不需要智能阻挡模式来提速？还是大批量的时候使用没有缓存的二合一接口智能阻挡更快一点？

**Comment by reobf** [comment]
不需要智能阻挡模式来提速

缓存二合一输入仓的机制是
1.没有锁定配方时，tick结束后将外缓内容物作为配方进行锁定（因此必须在单tick内完全发配）
2.锁定配方时，一旦检测到外缓有相同配方，瞬间移入内缓，因此不会被阻挡模式挡住，同tick可以继续发配直到并行耗尽

因此只需要1tick进行锁定，1tick进行转移

**Comment by reobf** [comment]
用不带缓的 可以开智能阻挡 取决于你

**Comment by PinkYuDeer** [comment]
酷！smat blocking go hell
