### ISSUE TITLE
Output hatch lag

### ISSUE THREAD

**Issue by TimberDimber** [reobf/Programmable-Hatches-Mod#101]
https://spark.lucko.me/GKhjPHqiSs

Noticed it about a month ago but thought it might be a problem on my side, so I decided not to focus on it. However, now it has started causing significant discomfort in the game. 
So: when I'm connecting an output hatch (2.7) directly to the main ME, the hatches themselves cause severe lag. 

(can see this in lag diapasons)
![image](https://github.com/user-attachments/assets/fdd43140-0c8d-4a8c-bc29-d77238d34ae4)
(All of this are output hatches)
![javaw_3yAExY8PAh](https://github.com/user-attachments/assets/442af437-5241-4e54-b023-af558212268e)
![cmd_kmaIKt2LaP](https://github.com/user-attachments/assets/74129842-df4a-4eb1-b008-ce8159d8c6ad)
![cmd_396J9gqTdx](https://github.com/user-attachments/assets/682d3049-fc0e-481a-b4ae-c9975ae4a84d)

If I set up the output hatch in a separate subnet (hatch -> tank -> export), the lag doesn’t display directly but is still noticeable as temporary spikes.  After running several tests through Spark, I discovered that the lag is indeed caused by this mod.

This is especially noticeable where crafts involve liquid output: chemical reactor, thermonuclear reactor, DTPF, alloy smelter, fluid heater, fluid extractor.

**Comment by reobf** [comment]
My badI did not cache the pattern, so it creates new pattern details every time it updates.Will fix it in next release

**Comment by reobf** [comment]
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/0.0.19p24-beta

**Comment by TimberDimber** [comment]
Much better. Thank you
![image](https://github.com/user-attachments/assets/2e190fc5-811d-46a9-afa3-31fb87e6d941)

https://spark.lucko.me/QbMtWmdU5S
