### ISSUE TITLE
缓存二合一仓室流体或者物品溢出的问题

### ISSUE THREAD

**Issue by Armelia-William** [reobf/Programmable-Hatches-Mod#105]
RT，可以看到流体没有锁住，因为电力缓存只能有一个仓室位置，所以只有使用二合一输入区映射镜像ME，但是这镜像和样板输入类似，没有阻挡模式，会导致这样不知道为何流体溢出一个缓存槽的现象，不知道怎么解决，没有倍乘样板，是只能使用不带缓存的版本吗，我看见#88也有类似的溢出问题。
![2024-11-14_23 43 04](https://github.com/user-attachments/assets/f3a40588-2dfe-40c3-b174-baf33f4e98df)

另外物品可能发生溢出的情况编程器电路占位，导致9格满的配方最后一格被挤到下一个缓存槽，顺带最后一格流体概率挤到下一个缓存槽，RT例如搅拌机配方，对于TST的深度扭曲化反，部分配方如聚氨酯树脂，编程器电路也会正好挤掉最后一格(UHV仓室)，虽然可以两者都可以用专门一个仓室来解决。
![2024-11-13_01 06 40](https://github.com/user-attachments/assets/33937e8a-79e1-4cfa-b008-a20768b78711)
![2024-11-13_01 06 56](https://github.com/user-attachments/assets/50eea8a9-f4ca-44dd-a2a3-bc8f13d481c7)

**Comment by reobf** [comment]
映射镜像ME 自带阻挡 

问题1：右上角那个缓存 锁定的配方是什么，是否包含了那个同流琥珀金外壳？换句话说 有没有显示非整数倍？
问题2：游戏版本 mod版本
问题3：一个生物超级电脑 我看是要10k超级冷却液 你那个版本是要多少？
问题4：映射镜像ME连接的那个仓，是否也连了接口，覆盖版接口还是面板接口？

**Comment by Armelia-William** [comment]
> 第一张图waila截图一下 或者传存档更直接一点..
![2024-11-15_00 36 55](https://github.com/user-attachments/assets/df7fb711-efc3-483c-9832-5e0db37e4669)
正好卡着的
链接: https://pan.baidu.com/s/1seNTQM_CGh11_iwBItdYwA?pwd=a3uz 提取码: a3uz

**Comment by reobf** [comment]
游戏版本 mod版本呢
有存档 其它问题我自己确认就好

**Comment by Armelia-William** [comment]
> 游戏版本 mod版本呢 有存档 其它问题 我自己确认就好
programmablehatches-0.0.19p24 版本是2.61

**Comment by reobf** [comment]
![2024-11-15_01 30 34](https://github.com/user-attachments/assets/cfc8b37b-3f52-4bc3-9b97-911979f6680b)
？

**Comment by reobf** [comment]
关于第二个问题 物品容量会给大方点的...
流体 没办法 int上限2.1g摆在哪里

**Comment by Armelia-William** [comment]
> 文件修改时间显示9月 之前也向你要过存档吧 是不是弄混发错了
我链接分享错了
链接: https://pan.baidu.com/s/12HfGfWtWJNFse4X0opGaRQ?pwd=5rz7 提取码: 5rz7

**Comment by Armelia-William** [comment]
> 关于第二个问题 物品容量会给大方点的... 流体 没办法 int上限2.1g摆在哪里

但其实物品容量是够的，他只有九个格子，编程电路挤掉一格就会挤走物品，多加一个堆叠为1的编程器槽？流体其实容量也是够的，问题是总量是够的，但是太多流体槽了，导致单个流体容量不够，比如ABCD流体，4096000mb*6的仓室，ABC都是 4096kmb+100，就会把D挤掉，尤其是缓存二合一仓室，在不倍乘样板的时候经常会把D流体挤进新的缓存。
那个ME流体/物品库存升级不知道有什么用

**Comment by Armelia-William** [comment]
> > 关于第二个问题 物品容量会给大方点的...流体 没办法 int上限2.1g摆在哪里
> 
> 但其实物品容量是够的，他只有九个格子，编程电路挤掉一格就会挤走物品，多加一个堆叠为1的编程器槽？流体容量其实也是够的，问题是总量是够的，但是太多流体槽了，导致单个流体容量不够，比如ABCD流体，4096000mb*6的仓室，ABC都是 4096kmb+100，就会把D挤掉，尤其是缓存二合一仓室，在不倍乘样板的时候经常会把D流体挤进新的缓存。 那个ME流体/物品库存升级不知道有什么用

因为样板输入总成实在很遥远，前面大部分都是ME接口/镜像的模式，这问题经常能遇到，因为单个容量流体槽不够，只有设置向空槽(从小到大输入)，但是又会把末尾的流体挤掉，二合一输入仓尤其明显，AE网络一股脑往缓存槽塞，到上限的时候就会挤掉

**Comment by reobf** [comment]
安全终端坐标

**Comment by reobf** [comment]
> 那个ME流体/物品库存升级不知道有什么用

给二合一集成一个 ME库存输入
比如高炉样板就不用写保护气  安装一个流体库存升级 标记气体就行
安装后电路槽会变成按钮 点一下就能打开

**Comment by Armelia-William** [comment]
> 安全终端坐标 找不到

XYZ -29 38 -469

**Comment by reobf** [comment]
> > 关于第二个问题 物品容量会给大方点的... 流体 没办法 int上限2.1g摆在哪里
> 
> 但其实物品容量是够的，他只有九个格子，编程电路挤掉一格就会挤走物品，多加一个堆叠为1的编程器槽？流体其实容量也是够的，问题是总量是够的，但是太多流体槽了，导致单个流体容量不够，比如ABCD流体，4096000mb*6的仓室，ABC都是 4096kmb+100，就会把D挤掉，尤其是缓存二合一仓室，在不倍乘样板的时候经常会把D流体挤进新的缓存。 那个ME流体/物品库存升级不知道有什么用

别看总量 总量不能说明问题
int上限约
2,100,000,000mb，一桶1k还要砍掉三个数量级
等于2,100,000桶
每个等级至少要翻个倍吧
从max往下算到uv这里就只能给那么多了
本来是一格子/一个槽对应一种物品/流体的
谁让GTNH数值膨胀那么厉害
物品数量膨胀的还没那么厉害，能通过给数值基本上保证一个格子一种物品
物品格数值确实给少了 你那几个基本上都是芯片堆到2048算满，流体还没顶到上限

**Comment by reobf** [comment]
要不然直接uhv封顶 更高级的直接砍掉 把数值下方到更低压的仓

**Comment by reobf** [comment]
机制就这样 很多地方就是用int的
换long要大改，而且是GTNH那边要大改

**Comment by reobf** [comment]
其实你用优先级过滤me输入的话 可以把16个物品子网+4个流体子网 连一起 也能正常运行
tooltip说的是针对普通me输入的

**Comment by reobf** [comment]
二合一输入区映射镜像ME 是自带阻挡的
而且流体注入策略用的是 目标仓的策略（空优先视为普通模式） 本身那个按钮没用

**Comment by Armelia-William** [comment]
> 其实你用优先级过滤me输入的话 可以把16个物品子网+4个流体子网 连一起 也能正常运行 tooltip说的是针对普通me输入的

这个是历史遗留问题，之前我配方重复物品还是改名状态，换了诱骗总线直连之后同一物品不同命名，我记得当时是没法合成，装配线检测不到配方，但是我又没弄清楚这个诱骗总线的用处，所以又改回了之前连个ME接口的方式。

**Comment by reobf** [comment]
> > 太魔法了 单次下单无法复现格子错位问题
> 
> 装配线这问题我确实没想到是啥原因引起的，按理说到了上限他就会不发放了 但是我实际自己用着是经常会显示不成整数倍的配方，但一般都能正常进去，但是极少部分又会出现这种挤出来一个的情况 复现又太久了，生产力不够下单估计要等好几个小时，没法稳定触发，平时基本不会出问题 但是量大之后疑似会出现问题。 其实今天我刚更新了电力，加装了三组) 此外我记得发生问题之前，装配线弹了那个报错：多个存储总线使用同一可能发生此错误 然后我又重新开了装配线，前面错位的流体我都用手填了，可能让流体发生了错位。

诱骗如果没有及时刷新 理论上可能会出现此问题
不知道261能不能改刷新频率
最好诱骗单独改1tick

**Comment by reobf** [comment]
才知道输出总线能用内存卡...

**Comment by reobf** [comment]
> > > > 太魔法了 单次下单无法复现格子错位问题
> > > 
> > > 
> > > 装配线这问题我确实没想到是啥原因引起的，按理说到了上限他就会不发放了 但是我实际自己用着是经常会显示不成整数倍的配方，但一般都能正常进去，但是极少部分又会出现这种挤出来一个的情况 复现又太久了，生产力不够下单估计要等好几个小时，没法稳定触发，平时基本不会出问题 但是量大之后疑似会出现问题。 其实今天我刚更新了电力，加装了三组) 此外我记得发生问题之前，装配线弹了那个报错：多个存储总线使用同一可能发生此错误 然后我又重新开了装配线，前面错位的流体我都用手填了，可能让流体发生了错位。
> > 
> > 
> > 诱骗如果没有及时刷新 理论上可能会出现此问题 不知道261能不能改刷新频率 最好诱骗单独改1tick
> 
> 嗯，我改下，此外还有一些小问题，我一起提一下吧 1、二合一输入镜像ME不小心打掉样板会直接被吞掉消失，不会掉出来 2、数量维持总线没法使用内存卡复制粘贴

不好意思忘说了这两个应该在某个版本加了

**Comment by Armelia-William** [comment]
> > > > > 太魔法了 单次下单无法复现格子错位问题
> > > > 
> > > > 
> > > > 装配线这问题我确实没想到是啥原因引起的，按理说到了上限他就会不发放了 但是我实际自己用着是经常会显示不成整数倍的配方，但一般都能正常进去，但是极少部分又会出现这种挤出来一个的情况 复现又太久了，生产力不够下单估计要等好几个小时，没法稳定触发，平时基本不会出问题 但是量大之后疑似会出现问题。 其实今天我刚更新了电力，加装了三组) 此外我记得发生问题之前，装配线弹了那个报错：多个存储总线使用同一可能发生此错误 然后我又重新开了装配线，前面错位的流体我都用手填了，可能让流体发生了错位。
> > > 
> > > 
> > > 诱骗如果没有及时刷新 理论上可能会出现此问题 不知道261能不能改刷新频率 最好诱骗单独改1tick
> > 
> > 
> > 嗯，我改下，此外还有一些小问题，我一起提一下吧 1、二合一输入镜像ME不小心打掉样板会直接被吞掉消失，不会掉出来 2、数量维持总线没法使用内存卡复制粘贴
> 
> 不好意思忘说了这两个应该在某个版本加了

之前我看见了，这个issue我先关了，如果后面我有遇到这种情况再说吧。
