### ISSUE TITLE
新旧编程器电路同时存在ae中时，旧版无法正常取出

### ISSUE THREAD

**Issue by Handsonzyx** [reobf/Programmable-Hatches-Mod#11]
当ae中同时存在新旧两种时，旧版的也会被识别成新版的，导致旧版的无法拿出。
解决方法为先把能拿出的全部拿出，ME-IO把剩余的旧版单独导入一个盘，这时会正常识别为旧版，可以拿出。
如果这个问题不打算解决的话建议在tooltips中增加提醒。

**Comment by reobf** [comment]
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/v0.0.15p4-beta
