### ISSUE TITLE
New Suggestion

### ISSUE THREAD

**Issue by evgengoldwar** [reobf/Programmable-Hatches-Mod#110]
Add the ability to adjust the maximum number of items or liquids stored in a chest

![image](https://github.com/user-attachments/assets/2924bf51-4d0e-4bd5-9f74-32272a53c151)

Also missing is the ability to clear nbt like normal chests do
![image](https://github.com/user-attachments/assets/caf3a29a-01b1-4ce6-87e0-0c980f0d6589)

![image](https://github.com/user-attachments/assets/d34c05ec-0db5-430e-9290-de8033e9b2fe)

![image](https://github.com/user-attachments/assets/ddf443a5-4ce3-4e98-af57-469c87c9d464)

**Comment by reobf** [comment]
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/0.0.19p29-beta
