### ISSUE TITLE
加了Programmable-Hatches-Mod后加载会卡住

### ISSUE THREAD

**Issue by Wood-Hammer** [reobf/Programmable-Hatches-Mod#112]
![屏幕截图 2024-12-03 143743](https://github.com/user-attachments/assets/40d92397-a52b-48aa-90da-a9c259a12805)
（只）加了Programmable-Hatches-Mod后加载到这会卡住
GTNH版本2.7.0-RC1和RC2都有这个问题
[fml-client-latest.log](https://github.com/user-attachments/files/17988812/fml-client-latest.log)
[latest.log](https://github.com/user-attachments/files/17988813/latest.log)
[crash-2024-12-03_14.35.43-client.txt](https://github.com/user-attachments/files/17988814/crash-2024-12-03_14.35.43-client.txt)

**Comment by reobf** [comment]
请用带gtnh270后缀的版本
因为270beta1之前的某个版本gtnh进行了一次破坏性更改
导致无法用一个jar文件同时支持261-和270

**Comment by Wood-Hammer** [comment]
使用GTNH270版本，问题已解决
