### ISSUE TITLE
能否为编程样板输入添加自动改名功能

### ISSUE THREAD

**Issue by Koamasi** [reobf/Programmable-Hatches-Mod#113]
原版样板总成/总线在添加额外物品(例如编程电路)后会自动改变接口名称 能否为编程样板输入也增加该功能

**Comment by reobf** [comment]
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/0.0.19p31-beta
感觉没啥用说实话
如果不是gt电路就会显示电路槽中物品完整名称 
然而此时不开强制unicode的话（字会窄一点） 名称基本上就占满了

**Comment by reobf** [comment]
已实现 先关了
