### ISSUE TITLE
能否增加一个ME板的固化仓

### ISSUE THREAD

**Issue by NNNNMMMMIIII** [reobf/Programmable-Hatches-Mod#114]
现在的固化仓容量太小，也没办法放电路板，固化机器本身并行就很大，根本没办法跑满

**Comment by reobf** [comment]
首先九合一270应该是淘汰了 大固化应该也不支持固化仓也用不到电路板了
其次如果是因为单缓冲仓 会被轮流发配两种不同配方导致堵住的话，可以试试看"合成转储器"(目前无配方)，这东西可以连续发配同一个配方而不是ae默认的优先发配不同配方

**Comment by reobf** [comment]
ae的默认行为是 把每一种待发配的样板遍历尝试一次 如果有成功发配的就再遍历一次 

导致结果就是优先发配不同样板雨露均沾

**Comment by NNNNMMMMIIII** [comment]
铂处理中的四氯化钌和氯化钙还需要1号电路板来固化，如果按256并行蒸馏塔一秒的产出就有36864桶四氯化钌需要固化

**Comment by NNNNMMMMIIII** [comment]
而且我试过主方块放1号电路板，然后放存储输入仓，结果不行
