### ISSUE TITLE
安装此mod后导致MFU无法连接GT机器

### ISSUE THREAD

**Issue by reobf** [reobf/Programmable-Hatches-Mod#115]
@PinkYuDeer
抱歉 我的问题 在修

**Comment by reobf** [comment]
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/0.0.19p32-beta
@PinkYuDeer 修了 再次表示抱歉

**Comment by PinkYuDeer** [comment]
我勒个豆hh 大佬好牛！！（是说mod真的好用以及修的速度以及（吃了个饭挂机回来之后发现实体8000个

**Comment by PinkYuDeer** [comment]
奥对了顺便那个 细菌真空仓 多方快 二合一会变色但是主机不认（

**Comment by reobf** [comment]
> 奥对了顺便那个 细菌真空仓 多方快 二合一会变色但是主机不认（

放一个输入仓满足输入仓>=1的要求就好

**Comment by PinkYuDeer** [comment]
原来如此
