### ISSUE TITLE
发信器控制板怎么用？

### ISSUE THREAD

**Issue by NNNNMMMMIIII** [reobf/Programmable-Hatches-Mod#116]
给原木拟生场贴上后根本连不上网络,各种线缆覆盖版都试过连不上去

**Comment by reobf** [comment]
https://github.com/user-attachments/assets/49d54663-dc13-43ba-8a8c-9a8a0865a4f1

**Comment by NNNNMMMMIIII** [comment]
问题是我试过了，填那个数量根本没用，我4M松木填个3M或者5M也一直启动，没有检测数量够了就停机

**Comment by NNNNMMMMIIII** [comment]
![屏幕截图 2024-12-08 224806](https://github.com/user-attachments/assets/fc038d4f-eeb5-45b0-90b8-e736a9cc02d1)
不开启条件填数字3M或者5M机器一直停机，开启条件就一直启动，即使数量填1或者一亿也一样

**Comment by NNNNMMMMIIII** [comment]
大化反怎么办，周围一圈玻璃根本贴不了东西？

**Comment by reobf** [comment]
> 大化反怎么办，周围一圈玻璃根本贴不了东西？

那拿普通ae发信器+控制覆盖版也没辙啊

除了无线红石或者oc控制没其它选择
