### ISSUE TITLE
Nei bug

### ISSUE THREAD

**Issue by evgengoldwar** [reobf/Programmable-Hatches-Mod#117]
This is a group with programmable hatches and if you delete it, several new ones appear. Also every time the game is started a new group appears. The group itself cannot be deleted

![image](https://github.com/user-attachments/assets/62bf7a56-6bfd-4514-9079-83b4ceaf9777)

**Comment by reobf** [comment]
Your NEI version?
NEI changed its preset API many times (actually no API at all, I use mixin to inject presets).
And accoring to latest NEI code, the presets support of my mod should be broken, rather than work incorrectly.

**Comment by reobf** [comment]
uh
Then just withdrew the 2.7.0 release....
I will just remove preset support in next release, until they make the code stable.

**Comment by reobf** [comment]
How to open this window?
I tried and fail to find how to.

**Comment by reobf** [comment]
Sorry for not knowing much about the new NEI.
I'm using 2.6.1 NEI as dev env.
So...
What's a 'group'?

**Comment by evgengoldwar** [comment]
> Sorry for not knowing much about the new NEI. I'm using 2.6.1 NEI as dev env. So... What's a 'group'?

I'm playing on RC2, 

Click this
![image](https://github.com/user-attachments/assets/cd1de1a4-eea1-46ad-ae90-a9fa76f89157)

![image](https://github.com/user-attachments/assets/b6c54b07-f318-4f8a-ac09-cd8ea2d02ba3)

![image](https://github.com/user-attachments/assets/b6b016cf-5f7f-4cf0-a503-231421225b6a)

**Comment by reobf** [comment]
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/0.0.19p33-beta
fixed, but only work in 270 stable
RC2 also fixed but has no collasped item support
