### ISSUE TITLE
ae下单部分流体配方不发货

### ISSUE THREAD

**Issue by PinkYuDeer** [reobf/Programmable-Hatches-Mod#119]
如图所示
![image](https://github.com/user-attachments/assets/cb6dca15-b34a-4674-a721-c2f8e84b6826)
![image](https://github.com/user-attachments/assets/ad7cf39e-7661-40ab-99da-bbe9b2b1f003)
![image](https://github.com/user-attachments/assets/33a6d212-350d-4da6-8226-1594d8cbb390)

**Comment by reobf** [comment]
9 桶邻苯二甲酸
1 K2Cr2oO7
54 桶氧气
9 桶邻二甲苯

K2Cr2oO7
总需要
两个铬
6桶氧气
8硝酸钾


54 桶氧气+6桶氧气=60桶氧气
9 桶邻苯二甲酸也是显示的
看起来是倍增前的数量......
是否是合成半途中倍增了样板...？

**Comment by PinkYuDeer** [comment]
不知道为啥但是修好了。
不是因为倍增，单独一个的时候也不发货。
之前的二氧化铬不发货了，但是检查的时候uv二合一没东西。
敲掉二合一重放就发货了（）然后就全能合成了（）奇奇怪怪的，但是好了:)

**Comment by PinkYuDeer** [comment]
我猜可能是因为我之前忘开阻挡模式乱进导致的（但是清理过一次二合一、打开阻挡模式重新下单，可能是接口里面有什么奇怪的东西残留了进到新的二合一里面了吧（猜的）
