### ISSUE TITLE
血魔法宝珠的问题

### ISSUE THREAD

**Issue by NNNNMMMMIIII** [reobf/Programmable-Hatches-Mod#12]
绑定过的宝珠AE不认，必须重新做一个才行

**Comment by reobf** [comment]
是否是在说使用宝珠生产仪式石的组装机配方？
如果是
绑定过的宝珠带有NBT，用工具箱直接编码的宝珠没有NBT，所以不被认为是一种物品
考虑过以下的解决方案：过在生成编程器电路时移除其NBT，这样确实能解决你遇到的问题
但考虑到游戏内存在 重命名模具的冲压机配方，这种配方不消耗物品的同时，需要依赖不消耗物品的NBT以正常工作，个人认为其应用应该比宝珠配方更广泛，暂时不考虑使用这种解决方案
因此，这是AE的特性**mod不会针对这个问题进行特殊处理** 请重新做一个宝珠，或者，你还可以选择用工具箱生成绑定宝珠的编程器电路来手动编写样板（即：提供器和样板都用绑定宝珠）
