### ISSUE TITLE
一条线中接入超过6个超级箱（ME）会导致服务器特别卡

### ISSUE THREAD

**Issue by addpromax** [reobf/Programmable-Hatches-Mod#121]
![fe07402c85485fce1097a8fa29e5d3c3](https://github.com/user-attachments/assets/e4a9a3ea-2949-4ba1-96c1-401bff1b6cd6)

**Comment by reobf** [comment]
唔 未能简单复现
不管是通电还是未通电tps都没有明显改变
可以考虑在卡的时候跑一下spark
mcmod使用介绍：https://www.mcmod.cn/class/4073.html
curseforge下载：https://mediafilez.forgecdn.net/files/4271/867/spark-1.10.19-forge1710.jar
把报告发上来供分析..

**Comment by addpromax** [comment]
经测试 应该是末影导管输入的问题导致频繁刷新ae 接入ae子网+me输入总线后正常了

**Comment by reobf** [comment]
检查了一下 确实会在通过物流输入物品时进行不必要的刷新
下个版本修正
