### ISSUE TITLE
Up capacity void hatch

### ISSUE THREAD

**Issue by evgengoldwar** [reobf/Programmable-Hatches-Mod#122]
![image](https://github.com/user-attachments/assets/1016fd69-9757-483c-bca4-5b555baac446)

![image](https://github.com/user-attachments/assets/1c3bb26e-9e01-4389-9e26-08a67028515d)

with void mode
![image](https://github.com/user-attachments/assets/1c5df18a-1707-4bb2-8373-8832c1050c5c)

**Comment by reobf** [comment]
void hatch has **no** capacity
It just removes matched fluid from outputs.

**Comment by reobf** [comment]
GT5u assumes that all output hatches only outputs **1** type of fluid(ME output hatch has special checks, that's an exception). 
So it won't work if I add capacity to void hatch.
It only lets 1 type of fluid bypass the voiding check, if you mark 2 types of fluid, things are broken.
So you have to trun off voiding protection, or add more output hatch to trick the parallel system to run.

**Comment by reobf** [comment]
As you can see, there's no Multioutput Hatch in GT5u, if GTNH dev did not provide such API, that's unlikely to be done.
