### ISSUE TITLE
发信控制控制板有BUG

### ISSUE THREAD

**Issue by NNNNMMMMIIII** [reobf/Programmable-Hatches-Mod#123]
里面标记的东西会变动，本来标记润滑油然后变成硝化甘油，绿色火箭燃料变成R1火箭燃料，松油变成独居石泡沫

**Comment by NNNNMMMMIIII** [comment]
GTNH270 mod 0.0.20
![屏幕截图 2024-12-15 161057](https://github.com/user-attachments/assets/33d7397d-be84-47b3-a0d5-9dde5f195561)

**Comment by reobf** [comment]
是重启服务端/客户端SL后出的问题吗
还是同一局游戏就会变
期间升级过gtnh版本吗

**Comment by NNNNMMMMIIII** [comment]
没升级过版本一样是270，不过mod19P33换成0.0.20，应该是重启才有这问题，因为我也就重启过几次，因为重启后发现燃料产量不正常才发现这bug

**Comment by NNNNMMMMIIII** [comment]
还有个bug，就是仓室容量足够但是AE就是放不进去
![屏幕截图 2024-12-15 172020](https://github.com/user-attachments/assets/1a590563-629f-4e20-93db-3879e8657d0a)
![屏幕截图 2024-12-15 172003](https://github.com/user-attachments/assets/2917b01f-d8eb-4b30-a47e-235a65ee8abd)
![屏幕截图 2024-12-15 171948](https://github.com/user-attachments/assets/c6c6b367-522c-4663-8116-56b5a94f9da6)
![屏幕截图 2024-12-15 171940](https://github.com/user-attachments/assets/df546b43-f9ed-49b9-b15f-1909d4ff9900)
![屏幕截图 2024-12-15 171905](https://github.com/user-attachments/assets/d8eaa9c3-be3f-4d8d-a7e5-951f7352c9fd)

**Comment by NNNNMMMMIIII** [comment]
![屏幕截图 2024-12-15 172444](https://github.com/user-attachments/assets/b530f865-77c6-4067-844c-5c416dbfc8ee)

**Comment by reobf** [comment]
就算是MA模式 也是要调流体输入策略的
现在在全面移植到270（放弃261支持）在大改代码 没法测 你先试试看能不能
![屏幕截图 2024-12-15 171948](https://github.com/user-attachments/assets/c6c6b367-522c-4663-8116-56b5a94f9da6)

**Comment by NNNNMMMMIIII** [comment]
试了下常规模式是没问题的，但是限制模式下只要你投料大于UI输入容量他就卡住，比如说IV二合一输入仓容量是256000l，但是输入超过256000l以后就不投了，直接卡住

**Comment by reobf** [comment]
MA模式只是利用分子装配的api 把样板数据传递给仓室(从而避免一份材料进两个缓冲)
并不能突破常规模式原有的限制
事实上 限制模式不能发配 正是MA模式正确工作的一种表现(常规模式就直接乱配方了)

**Comment by reobf** [comment]
至于覆盖板的问题
推测应该是gt的流体id变化了
然后存盘的是流体id 再加载就乱了
270从rc升级到正式版 或单独更新mod也有可能改变id

下个版本额保存一下流体字符串id吧 应该能避免这种情况
