### ISSUE TITLE
261版本升级0.0.20后库存升级不兼容多方块结构

### ISSUE THREAD

**Issue by Koamasi** [reobf/Programmable-Hatches-Mod#125]
如下图所示
![3e03ff631c872a502502d8aa82779806](https://github.com/user-attachments/assets/12faf8ea-9aa8-4221-a937-aae91503b65e)

**Comment by Koamasi** [comment]
这是服务器日志
[fml-server-latest.log](https://github.com/user-attachments/files/18177927/fml-server-latest.log)

**Comment by reobf** [comment]
我另一个mod是这个mod改的   一些遗留代码冲突了
更新了 尝试重新下载vmtweak试试

**Comment by reobf** [comment]
或者你把他vmtweak移除了试试

**Comment by reobf** [comment]
不装vmtewak
261+0.0.20是ok的
https://github.com/user-attachments/assets/8857c0e2-1e9d-436c-8576-33f026e5a6bd

**Comment by Koamasi** [comment]
更新vmtweak之后正常了 感谢喵
