### ISSUE TITLE
ME覆盖版无法向ME仓室传递频道

### ISSUE THREAD

**Issue by Handsonzyx** [reobf/Programmable-Hatches-Mod#13]
ME覆盖版不能贴在ME仓室上，也不能向ME仓室传递频道，希望贴了ME覆盖版的仓室能像ME仓室那样互相传递频道。

**Comment by reobf** [comment]
下个版本 编程样板输入总成/总线 可以像原版总成一样用剪线钳使其六面都可以连接ME网络
ME覆盖版不能贴在自身消耗频道的机器上，是有意而为的设计，因为ME覆盖版的频道实际上并没有“穿入”所贴的机器，实际上是不连接机器本身的频道的，如果贴在ME仓室不能连接ME网络的一面是无法连通的，为防止不符合直觉的行为所以干脆直接禁止了
剪线钳允许六面连接应该能临时解决这个问题，ME覆盖版贴ME仓室的功能可能需要进一步测试暂时无法实现

**Comment by reobf** [comment]
下个版本 编程样板输入总成/总线 可以像原版总成一样用剪线钳使其六面都可以连接ME网络
ME覆盖版不能贴在自身消耗频道的机器上，是有意而为的设计，因为ME覆盖版的频道实际上并没有“穿入”所贴的机器，实际上是不连接机器本身的频道的，如果贴在ME仓室不能连接ME网络的一面是无法连通的，为防止不符合直觉的行为所以干脆直接禁止了
剪线钳允许六面连接应该能临时解决这个问题，ME覆盖版贴ME仓室的功能可能需要进一步测试暂时无法实现

**Comment by reobf** [comment]
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/v0.0.15p6-beta
新版剪线钳使其六面都可以连接ME网络
ME覆盖版也可以贴ME仓室，但需要在Config里面把“MECover on MEHatch”选项设为true（默认关闭）
