### ISSUE TITLE
Level control cover

### ISSUE THREAD

**Issue by evgengoldwar** [reobf/Programmable-Hatches-Mod#133]
How can the coverage level control network be connected if the multiblock controller is out of range?

![image](https://github.com/user-attachments/assets/73faf024-f60f-4262-a2ec-8d8ac2300d37)

**Comment by reobf** [comment]
Use  ME cover
For example, 
one level control cover on top of controller
one ME cover on bottom of controller
one ME  on top of drone downlink
one ME on front of dronr downlink
now you can connect cable

**Comment by reobf** [comment]
Blame GT5u for not allowing cover on front side.

**Comment by reobf** [comment]
For single block machine you have to use at least ME cover.
If the machine/hatch itself has a ME node, cover will check it, otherwise check the ME network of ME cover on the block(if there is one).

**Comment by evgengoldwar** [comment]
> Use ME cover For example, one level control cover on top of controller one ME cover on bottom of controller one ME on top of drone downlink one ME on front of drone downlink now you can connect cable

Yeah, it worked. When I tried it, I did this
one level control cover on bottom of controller
one ME on top of drone downlink
one ME on front of drone downlink
