### ISSUE TITLE
关于me输入仓/总线

### ISSUE THREAD

**Issue by Cori885** [reobf/Programmable-Hatches-Mod#134]
能否让me输入舱室支持矿典卡，更方便的过滤物品

**Comment by reobf** [comment]
子网用存储总线+矿辞卡
现在（270的功能）存储总线支持 读取过滤了（以前只有写入过滤）

**Comment by Cori885** [comment]
> 子网用存储总线+矿辞卡 现在（270的功能）存储总线支持 读取过滤了（以前只有写入过滤）

谢谢，不知道270更新了读取功能，这样简洁很多了
