### ISSUE TITLE
0.0.15p4版本在地震仪分析成书打开崩溃

### ISSUE THREAD

**Issue by tsunami2576** [reobf/Programmable-Hatches-Mod#14]
0.0.15p4版本在地震仪分析矿脉之后打印成书，书名并非斜体，并且打开就会崩溃，错误报告显示为该模组导致，尚未测试最新版是否修复

**Comment by reobf** [comment]
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/v0.0.15p6-beta
打开任意成书会崩端是mod的问题，但打印成书书名并非斜体应该不是mod的问题
尝试修复了前者，后者有没有解决可以尝试新版看看
