### ISSUE TITLE
预构电路提供器(透镜)有bug

### ISSUE THREAD

**Issue by NNNNMMMMIIII** [reobf/Programmable-Hatches-Mod#17]
AE显示有透镜但制作时候显示缺透镜，版本0.0.16

**Comment by reobf** [comment]
1.请问透镜类型
2.是直接下单透镜电路显示缺失，还是其他样板间接需求时显示缺失（是从矿物辞典遍历获取透镜的，一些奇怪的透镜可能未包含）

**Comment by NNNNMMMMIIII** [comment]
补充一下，所有的预制电路提供器都一样问题，单制作编程电路没问题但下单做其他
就一定显示会缺
![屏幕截图 2024-06-21 124959](https://github.com/reobf/Programmable-Hatches-Mod/assets/164090019/e1010570-bb95-459f-9471-dc60f0ca938c)
![屏幕截图 2024-06-21 125101](https://github.com/reobf/Programmable-Hatches-Mod/assets/164090019/9afe6bc8-d358-44bd-b268-c02a364ab68b)

**Comment by reobf** [comment]
![TRAQ1SL6AX{(`Y4SG$I $(N](https://github.com/reobf/Programmable-Hatches-Mod/assets/117543727/6cc7e5e1-ee15-4ad5-b6ec-4252c0ba17dc)
2.6.1 java8未能复现
再请问 java版本
以及整合包版本

**Comment by reobf** [comment]
先单独下单获取透镜电路， 再下单需要透镜电路的单子
是否能正常运行？

**Comment by reobf** [comment]
> 单制作编程电路没问题但下单做其他
> 就一定显示会缺
意思是先单独制作所需透镜电路，然后下单需要透镜电路的单子就能正常运行吗

**Comment by NNNNMMMMIIII** [comment]
刚好是2.6.1 JAVA8 0.0.16
试了下不行，仓库里的透镜不认的，其他所有预制电路也不认，但是正常用4个格子的编程电路就没问题

**Comment by reobf** [comment]
是否能手持不能用的透镜电路 输入/ct hand 截个图（或者其他输出nbt标签的手段也可以）

**Comment by NNNNMMMMIIII** [comment]
你把预制电路拆了，就算什么不放,ae又认之前制作的透镜

**Comment by reobf** [comment]
你的样板开矿词匹配了吗
以及
存档能提供一下吗（网盘或者 奶牛快传/文叔叔 这种临时文件转储网站）

**Comment by reobf** [comment]
> ![屏幕截图 2024-06-21 140859](https://private-user-images.githubusercontent.com/164090019/341658556-086a5da0-9444-4b99-84d1-00e39299e762.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NTA0ODUsIm5iZiI6MTcxODk1MDE4NSwicGF0aCI6Ii8xNjQwOTAwMTkvMzQxNjU4NTU2LTA4NmE1ZGEwLTk0NDQtNGI5OS04NGQxLTAwZTM5Mjk5ZTc2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMVQwNjA5NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDdhOGY1ZjI4ZTgzM2UxM2M2ZmQ1YjI2MjAzYmFkNGU5OGI1OTkyZTA5ZGQ5ZGEwOTg5MmVmNzkxZTQxNmY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.k7V36KBFll3ted0KLFhbY6FaKUG8Qd5XvJYXg9CJ0kk)

我的意思是透镜的编程器电路

**Comment by NNNNMMMMIIII** [comment]
![屏幕截图 2024-06-21 141345](https://github.com/reobf/Programmable-Hatches-Mod/assets/164090019/80850a01-4b7c-42e9-b2a3-037b393760de)

**Comment by NNNNMMMMIIII** [comment]
怎么给？

**Comment by reobf** [comment]
可以传 网盘/奶牛快传/文叔叔 麻烦你了
如果能同时提供游戏存档就再好不过了

**Comment by NNNNMMMMIIII** [comment]
![Uploading 屏幕截图 2024-06-21 142706.png…]()
是这个么？

**Comment by NNNNMMMMIIII** [comment]
![屏幕截图 2024-06-21 142706](https://github.com/reobf/Programmable-Hatches-Mod/assets/164090019/1767db10-b9e9-4566-a6e1-d67f643b83fd)

**Comment by reobf** [comment]
应该是

**Comment by NNNNMMMMIIII** [comment]
链接：https://pan.baidu.com/s/1l06MX4tajoWvzXqfsQUwxQ?pwd=e6d0 
提取码：e6d0

**Comment by reobf** [comment]
```
[08:40:49] [Server thread/INFO]: This world was saved with mod programmablehatches version 0.0.15p5 and it is now at version 0.0.15p8, things may not work well
[08:40:49] [Server thread/INFO]: This world was saved with mod TwistSpaceTechnology version 0.4.30-2.6.1fitted-test and it is now at version 0.4.30-GTNH2.6.0-final, things may not work well
```
首先你似乎是使用了0.0.15p8版本（而非0.0.16版）？
而且似乎你的存档原来是tst 261版本的，却回退到tst 260版本了？
这么做的原因是否是遇到了什么崩溃问题？
