### ISSUE TITLE
覆盖版ME接口无法从无线通用终端放入/取出样板

### ISSUE THREAD

**Issue by Handsonzyx** [reobf/Programmable-Hatches-Mod#18]
16p1
可以在接口终端看到，但是无法进行交互

**Comment by Handsonzyx** [comment]
![QQ截图20240622120221](https://github.com/reobf/Programmable-Hatches-Mod/assets/90818327/6f30b3a9-612e-457a-a12d-a673123e1113)
以及有办法能让覆盖版接口从总线的这个UI直接打开么

**Comment by reobf** [comment]
1.下个版本修
2.试试看 不保证会加 因为gt用的modularUI和ae的GUI不是一个体系

**Comment by reobf** [comment]
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/v0.0.16p2-beta
1.修了
2.能点击打开 但不是悬浮窗口 按esc直接退出

**Comment by reobf** [comment]
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/v0.0.16p2-beta
1.修了
2.能点击打开 但不是悬浮窗口 按esc直接退出
