### ISSUE TITLE
16p1 ME量子箱 会导致网络物品交互异常

### ISSUE THREAD

**Issue by Eticeweng** [reobf/Programmable-Hatches-Mod#19]
我的ME网络是主网与存储子网分离的，由子网提供接口给予主网进行交互

当子网连接上ME量子箱的时候，处于主网的 存储输入总线(ME) 会把所有的被标记的物品数量错误地汇报为 2.1G

!!!!**且会让读取该输入总线的机器以为真的有这么多原料而凭空工作产出**!!!!
![image](https://github.com/reobf/Programmable-Hatches-Mod/assets/43090280/cb126729-f3e6-445d-9946-bda3003ac50e)

**且当量子箱同时启用粘性模式的时候会导致ME网络无法通过ME终端写入物品**
https://github.com/reobf/Programmable-Hatches-Mod/assets/43090280/039d52b3-447d-4493-9883-87d10e5fdb4c

**Comment by Eticeweng** [comment]
这是物品无中生有的复现
https://github.com/reobf/Programmable-Hatches-Mod/assets/43090280/6c47841c-6e9c-4046-b77f-6a458616fd86

**Comment by Eticeweng** [comment]
这是无中生有的复现，文件过大无法上传到GitHub所以这里用外链了
https://drive.google.com/file/d/10ewWQbEK1v2CunnN1eVC0wwKRxKykQsb/view?usp=sharing

**Comment by reobf** [comment]
复现了 这两个问题都是都是同一处代码导致的 十分抱歉犯了低级错误
下个版本修复 大概今天24:00前

**Comment by reobf** [comment]
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/v0.0.16p2-beta
