### ISSUE TITLE
tooltips描述错误？

### ISSUE THREAD

**Issue by Handsonzyx** [reobf/Programmable-Hatches-Mod#20]
![QQ截图20240624135853](https://github.com/reobf/Programmable-Hatches-Mod/assets/90818327/08a16f25-e768-4a5f-983c-f36a82a494f1)
这个2048格应该是描述错误吧，是16格x2048容量？

**Comment by reobf** [comment]
下个版本更正

**Comment by reobf** [comment]
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/v0.0.16p3-beta
