### ISSUE TITLE
关于编程器覆盖板和共享输入总线的交互行为

### ISSUE THREAD

**Issue by Y0ungSea** [reobf/Programmable-Hatches-Mod#21]
在俩个相同频道且都安装编程覆盖板的共享输入总线中放入编程电路板，永远只有其中一个共享输入总线改变了电路板编号。这种行为是在预期内的吗？

**Comment by reobf** [comment]
是 因为写入虚拟电路板的同时 会立刻消耗掉 编程器电路
看看能不能对ggfab共享输入总线做特殊处理吧

**Comment by reobf** [comment]
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/v0.0.16p3-beta
加了共享输入总线镜像覆盖板解决这个问题
其中一个共享输入总线镜像贴**编程器覆盖板**
剩余所有同频道共享输入总线贴**共享输入总线镜像覆盖板**
那么电路板槽就能在它们之间共享
由于共享输入总线本身的特性(数据存储在当前世界数据中 没有“主”/“从”总线之分)只能这么实现

**Comment by Y0ungSea** [comment]
爱你（
