### ISSUE TITLE
ME超级箱、超级缸对priority card的兼容问题

### ISSUE THREAD

**Issue by Handsonzyx** [reobf/Programmable-Hatches-Mod#22]
![QQ截图20240625223613](https://github.com/reobf/Programmable-Hatches-Mod/assets/90818327/2519f38b-cb36-48a2-bb94-569f5ea3b788)
260新加入了priority card，方便对优先级查看、修改等，目前ME超级箱、超级缸暂时与该工具不兼容，后续是否会考虑进行兼容。

**Comment by reobf** [comment]
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/v0.0.16p3-beta
添加支持了
顺带一提覆盖版接口系列暂时不支持该工具
