### ISSUE TITLE
ME覆盖版在网络可视化下不可见

### ISSUE THREAD

**Issue by Handsonzyx** [reobf/Programmable-Hatches-Mod#25]
![QQ截图20240630150137](https://github.com/reobf/Programmable-Hatches-Mod/assets/90818327/6f964e72-876e-44d8-91db-da301f63b4a1)
中间两个方块是贴了ME二合一覆盖版的，而且ae能识别并正常下单，但是在网络可视化工具下无法看到连线

**Comment by reobf** [comment]
这个没办法 因为 覆盖板的节点实际上是虚拟的 没有实际坐标
