### ISSUE TITLE
ME超级箱V命名错误

### ISSUE THREAD

**Issue by Handsonzyx** [reobf/Programmable-Hatches-Mod#26]
![QQ截图20240630154431](https://github.com/reobf/Programmable-Hatches-Mod/assets/90818327/ec298d00-afc5-4b7c-a444-438c3008586d)
图中是超级箱V不是量子箱V

**Comment by reobf** [comment]
了解了 下个版本修复

**Comment by reobf** [comment]
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/v0.0.17p2-beta
