### ISSUE TITLE
16p2 ME量子缸会导致网络流体异常

### ISSUE THREAD

**Issue by Eticeweng** [reobf/Programmable-Hatches-Mod#27]
这个疑似跟#19 一样刷物品的问题，只不过物品变成了流体
当网络中存在连接到网络的

异常，往网络中放入流体不会扣减容器中的流体但是会在对应的存储设备中凭空生成流体（连接到量子缸）：
https://drive.google.com/file/d/1ryWv0zRWLjxBekZW83vpt8ITh_2l7xSy/view?usp=sharing
https://drive.google.com/file/d/1WcP0GvI_8PdpQG1up69fcaiIPP3Agyxg/view?usp=sharing

不扣减的情况仅会发生在使用1000mB的单元的情况下，使用诸如容量瓶的容器仍会正常扣减

跟 #19 里面疑似也会出现流体无法写入网络的情况，但是重新连接过ME量子缸之后就正常了

**Comment by reobf** [comment]
恭喜你发现了Bartworks的胶囊 流体复制bug~
你可以去gtnh那边提issue
这次不是我的问题，纯净gtnh也这样
复现过程为 输入仓-存储总线-流体终端-能源元件 在流体终端点击Bartworks的任意流体胶囊就能复制流体

**Comment by Eticeweng** [comment]
明白了，我再研究下，感谢回复
