### ISSUE TITLE
ME覆盖版贴在钢框架上导致游戏崩溃

### ISSUE THREAD

**Issue by Handsonzyx** [reobf/Programmable-Hatches-Mod#30]
[crash-2024-07-03_20.31.25-server.txt](https://github.com/user-attachments/files/16084930/crash-2024-07-03_20.31.25-server.txt)

**Comment by Handsonzyx** [comment]
17p3

**Comment by reobf** [comment]
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/v0.0.17p4-beta

**Comment by Handsonzyx** [comment]
> https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/v0.0.17p4-beta

[crash-2024-07-06_09.45.55-client.txt](https://github.com/user-attachments/files/16114610/crash-2024-07-06_09.45.55-client.txt)
17p4会导致游戏加载崩溃

**Comment by reobf** [comment]
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/v0.0.17p5-beta
再试试吧
