### ISSUE TITLE
关于 ME 量子/超级 箱/缸 的 物品/流体 标记功能建议

### ISSUE THREAD

**Issue by Eticeweng** [reobf/Programmable-Hatches-Mod#31]
能否考虑为 ME 量子/超级 箱/缸 添加 物品/流体 的标记功能？

可编程仓室的功能十分强大，能够直接连接到ME网络的 量子/超级 箱/缸 也是，
想将其当作AE网络下的大宗存储元件使用（或许会提供更好的性能？），
但是当其中 粘性模式打开 后 物品/流体（特别是流体） 消耗完毕之后会使得网络失去存储该物质的能力，
也会因为无法标记使得配置的时候更为麻烦（需要放入1个/mB的物质来标记）

如果已经包含了该功能希望能够提供一下说明，谢谢

**Comment by reobf** [comment]
![SQ3EI{C74~577BO 4YEF 3](https://github.com/reobf/Programmable-Hatches-Mod/assets/117543727/cf091272-e763-424f-a947-2ce61630b505)
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/v0.0.17p5-beta
原版ae粘性卡的特性如此，空容器无法加入新物品，流体存储总线+粘性卡+锁定流体的超级缸 也无法接受新流体
加了个选项在容器为空时 自动临时禁用粘性 允许新物品进来
但 没法记录之前的物品/流体类型（似乎数量为0的物品/流体 不被粘性模式认可 还是进不了新流体，保留一个物品/1mb流体又太难受）

**Comment by reobf** [comment]
![SQ3EI{C74~577BO 4YEF 3](https://github.com/reobf/Programmable-Hatches-Mod/assets/117543727/cf091272-e763-424f-a947-2ce61630b505)
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/v0.0.17p5-beta
原版ae粘性卡的特性如此，空容器无法加入新物品，流体存储总线+粘性卡+锁定流体的超级缸 也无法接受新流体
加了个选项在容器为空时 自动临时禁用粘性 允许新物品进来
但 没法记录之前的物品/流体类型（似乎数量为0的物品/流体 不被粘性模式认可 还是进不了新流体，保留一个物品/1mb流体又太难受）

**Comment by Eticeweng** [comment]
谢谢你的回复

或许是我描述的过于模糊，
应该是为 缸/箱 提供一个能够标记对应存储物的功能，类似于 存储总线/流体存储总线/存储元件 的标记功能
也就是把 存储总线/流体存储总线/存储元件 的标记功能集成在 缸/箱 之中
![image](https://github.com/reobf/Programmable-Hatches-Mod/assets/43090280/20951a04-a13c-4cc1-82e5-23cdfa78a5e2)
->
![image](https://github.com/reobf/Programmable-Hatches-Mod/assets/43090280/7bad0ff5-a8a4-43fb-851a-755e8f0c2a84)


而 **不是** 在存储物被消耗完毕时允许 新的别的物品/流体 进入

**Comment by Eticeweng** [comment]
没看见编辑标记，明白了，谢谢回复

**Comment by reobf** [comment]
> 没看见编辑标记，明白了，谢谢回复
加过滤标记了
有标记的情况下 开启粘性模式，无论容器是否是空的都能存标记的东西
之前没意识到粘性模式还有这么个机制
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/v0.0.17p6-beta
