### ISSUE TITLE
远程输入总线在绑定超级箱、抽屉、桶等容器时，物品占用第二格。

### ISSUE THREAD

**Issue by Handsonzyx** [reobf/Programmable-Hatches-Mod#33]
导致远程输入总线无法用于装配线。

**Comment by Handsonzyx** [comment]
另远程输入总线会导致进阶装配线出问题。

**Comment by reobf** [comment]
> 导致远程输入总线无法用于装配线。

因为这些东西内部槽位编号就不是第一个


> 另远程输入总线会导致进阶装配线出问题。

细说

**Comment by Handsonzyx** [comment]
> > 导致远程输入总线无法用于装配线。
> 
> 因为这些东西内部槽位编号就不是第一个
> 
> > 另远程输入总线会导致进阶装配线出问题。
> 
> 细说

进装用远程输入总线会崩溃
![QQ图片20240712175251](https://github.com/user-attachments/assets/dc03431c-16bf-43b8-babb-21e7fb4f8b30)

**Comment by reobf** [comment]
能发一下log吗
是否将两个输入总线绑到同一个容器里面了？

**Comment by Handsonzyx** [comment]
[latest.log](https://github.com/user-attachments/files/16192221/latest.log)
绑定的是无尽箱子

**Comment by Handsonzyx** [comment]
[latest.log](https://github.com/user-attachments/files/16192312/latest.log)
容器为无尽箱子，具体表现为不断吞第一个总线内的物品

**Comment by Handsonzyx** [comment]
最后第一个总线内的物品消耗完，但是只输出了一份产物

**Comment by reobf** [comment]
看起来是无尽箱子声称自己有244个格子，但实际上只有243格，而且访问第244格内容时会直接报错而不是返回null
无尽箱子第244格可能是用来实现某些特殊功能的
其它容器应该没有问题
下个版本看看能不能兼容

**Comment by reobf** [comment]
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/v0.0.17p8-beta
修了连接无尽箱会崩主控的问题
应该和进阶装配线没关系

连接 超级箱、抽屉、桶无法工作的问题
是因为装配线吃第一格物品，而非第一个非空的格子内物品
是gt5的特性，暂时不会针对这个问题做特殊处理
