### ISSUE TITLE
远程输入仓不支持的机器

### ISSUE THREAD

**Issue by Handsonzyx** [reobf/Programmable-Hatches-Mod#35]
暂时发现超级热交换机不支持远程输入仓，能成型但是无法正常启动合成。
后续有新发现的不支持的机器也会在此issue更新。

**Comment by reobf** [comment]
不支持列表
- 超级热交换机(Extreme Heat Exchanger)
- 热交换机(Heat Exchanger)

远程输入仓使用了ME输入仓也用到的的API，热交换机及其变种没有正确支持这个API(热交换机不支持ME输入仓)
无法修复，GTNH官方让热交换机支持ME输入仓后自然支持

**Comment by reobf** [comment]
修了
https://github.com/GTNewHorizons/GT5-Unofficial/pull/3271

**Comment by reobf** [comment]
应该支持了
https://github.com/GTNewHorizons/GT5-Unofficial/pull/3271
