### ISSUE TITLE
远程输入总线的bug

### ISSUE THREAD

**Issue by Handsonzyx** [reobf/Programmable-Hatches-Mod#36]
![QQ截图20240714025151](https://github.com/user-attachments/assets/2d6db47c-ec28-4f79-9334-d99fec0fe285)
远程输入总线在合成开始时会将虚拟电路槽重置

**Comment by reobf** [comment]
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/v0.0.17p8-beta
修了
