### ISSUE TITLE
编码样板输入总成的BUG

### ISSUE THREAD

**Issue by NNNNMMMMIIII** [reobf/Programmable-Hatches-Mod#38]
剪线钳右键输入总成设置成与任意面连接后这个设置不保留，出去再进存档就直接变成默认状态，每次进了存档后都要用剪线钳点一下

**Comment by NNNNMMMMIIII** [comment]
![屏幕截图 2024-07-16 081129](https://github.com/user-attachments/assets/2f18f069-8cd3-4397-b36e-5f716d71ddcc)
![屏幕截图 2024-07-16 081327](https://github.com/user-attachments/assets/44405890-8fdd-42f2-8560-51186dc3e0d5)
前一张是下线前，后一张是重新存档

**Comment by reobf** [comment]
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/v0.0.17p9-beta
修了
