### ISSUE TITLE
编程工具箱导致nei拉取配方出现错误

### ISSUE THREAD

**Issue by Handsonzyx** [reobf/Programmable-Hatches-Mod#4]
![屏幕截图 2024-06-01 103620](https://github.com/reobf/Programmable-Hatches-Mod/assets/90818327/494e900c-1132-4376-8a95-a98fcca05ca1)

背包有编程工具箱，从nei拉取合成台配方是配方会出现奇怪的错位

**Comment by reobf** [comment]
将在下一个release中修复

**Comment by reobf** [comment]
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/v0.0.15-beta
