### ISSUE TITLE
右键打开远程输入仓导致崩溃

### ISSUE THREAD

**Issue by Handsonzyx** [reobf/Programmable-Hatches-Mod#40]
[crash-2024-07-21_13.35.11-server.txt](https://github.com/user-attachments/files/16323189/crash-2024-07-21_13.35.11-server.txt)
远程输入仓用在电装上

**Comment by Handsonzyx** [comment]
好像是绑定了错误的东西导致的，我这个貌似不小心绑到ME箱子去了

**Comment by reobf** [comment]
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/v0.0.17p10-beta
修了
原因是ME箱子在没有流体盘时，会直接返回null而不是空的流体数据表 加了额外检测
