### ISSUE TITLE
ME接口覆盖版的改名功能失效

### ISSUE THREAD

**Issue by Handsonzyx** [reobf/Programmable-Hatches-Mod#41]
p10版本，无论是在覆盖版的GUI还是接口终端的GUI，都无法打开改名GUI进行改名

**Comment by reobf** [comment]
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/v0.0.17p11-beta
应该修了
新的实验性功能和重命名功能的网络包id写重复了...
