### ISSUE TITLE
AE输入总成的建议

### ISSUE THREAD

**Issue by foxwhite25** [reobf/Programmable-Hatches-Mod#42]
Shift 点击物品时，如果是样板应该直接进入样板物品栏，如果样板物品栏已满才进入普通物品栏，现在这样搬运样板到新系统可太难受了。

**Comment by reobf** [comment]
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/v0.0.17p12-beta

提了shift优先级

**Comment by foxwhite25** [comment]
好好好
