### ISSUE TITLE
编程样板输入总成放样板有点难受

### ISSUE THREAD

**Issue by NNNNMMMMIIII** [reobf/Programmable-Hatches-Mod#43]
本来编程样板就不好放，用快捷键就直接进缓存里面，只能一个个点很麻烦，无线终端又不能打拼音简单写，只能每次都回家用那个接口终端才行，机器挪位置放重新样板真的难受，不知道能否优化一下

**Comment by reobf** [comment]
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/v0.0.17p12-beta
现在打开窗口shift点击应该是优先进样板而不是缓存了
