### ISSUE TITLE
大型编程器电路提供器有问题特别卡

### ISSUE THREAD

**Issue by NNNNMMMMIIII** [reobf/Programmable-Hatches-Mod#44]
如果造东西的数量特别多的话就非常卡，不管样板是否翻倍或者减少透镜的数量一样会出现TPS爆降低，我就点蚀刻精致钻石就这一个东西就感觉打开任何东西都卡，造的数量越大越明显，版本是17P12

**Comment by NNNNMMMMIIII** [comment]
就是更新版本后只要AE一下单就卡的不行，后来我点了10M蚀刻精致钻石后发现一样卡，然后我看着AE任务里的透镜一旦做完就变流畅了

**Comment by reobf** [comment]
能提供一下存档吗
否则不太好判断...

**Comment by reobf** [comment]
或者，如果可以的话 你也可以在出现卡顿的时候跑一下spark性能分析
然后发一下报告
这边简单试了一下没能复现，需要更多信息 谢谢
https://www.curseforge.com/minecraft/mc-mods/spark/files/all?page=1&pageSize=20&version=1.7.10&showAlphaFiles=show

/spark profiler --start 开启分析
/spark profiler --stop 结束并生成报告

**Comment by NNNNMMMMIIII** [comment]
链接: https://pan.baidu.com/s/16EiCaCZVEbjdF5mS-a2xKA?pwd=aepd 提取码: aepd
开始分析之后我就跑了一下卡电脑的配方就结束了

**Comment by reobf** [comment]
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/v0.0.17p13-beta
改善了一点 可能还是有问题
顺带问一下，之前用得不卡的旧版本是？

**Comment by NNNNMMMMIIII** [comment]
17p10升级到17p12，现在回去17p10版本测试了下，同样的配方在17p10版本下有点卡，起码还做到AE秒开，地图还能加载出来，没17p12那么离谱
