### ISSUE TITLE
io枢纽的问题

### ISSUE THREAD

**Issue by P0lar1z2** [reobf/Programmable-Hatches-Mod#49]
![image](https://github.com/user-attachments/assets/ee180699-55ab-4dde-a648-3c7375f4d823)

这样摆放 
二合一贴着io枢纽 然后发一个配方会崩服
[crash-2024-08-08_23.39.55-server.txt](https://github.com/user-attachments/files/16550537/crash-2024-08-08_23.39.55-server.txt)

**Comment by P0lar1z2** [comment]
![image](https://github.com/user-attachments/assets/7f94705a-4bc8-4c21-adb2-f0be658f38e9)
复现成功
[crash-2024-08-08_23.54.42-server.txt](https://github.com/user-attachments/files/16550592/crash-2024-08-08_23.54.42-server.txt)

**Comment by reobf** [comment]
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/v0.0.18p4-beta
修了
