### ISSUE TITLE
更新后编程器电路与之前版本不通用

### ISSUE THREAD

**Issue by Handsonzyx** [reobf/Programmable-Hatches-Mod#5]
最新版的编程器电路与之前不同，导致所有用到编程器电路样板都需要重新修改

**Comment by Handsonzyx** [comment]
进一步测试发现ae无法识别新生成的编程器电路，总是提示缺少

**Comment by reobf** [comment]
新版本编程器电路的tag还额外记录了物品的字符串ID，来避免数字ID映射的物品发生变动，tag不同被认为是不同物品
下个版本会给提供器临时加入生产旧版编程电路的选项

**Comment by Handsonzyx** [comment]
但是新版中，新生成的编程电路似乎无法被ae正确识别，我用新的编程电路写样板，ae中也存入新生成的编程电路，下单时依然提示缺少编程电路

**Comment by reobf** [comment]
0.0.14p3没能复现...等新版再试试吧

**Comment by Handsonzyx** [comment]
![QQ截图20240603123654](https://github.com/reobf/Programmable-Hatches-Mod/assets/90818327/d894ed53-c714-4292-82ab-2be8f7ec5f52)
![QQ截图20240603123640](https://github.com/reobf/Programmable-Hatches-Mod/assets/90818327/0e1dc990-ee92-4b79-93a1-c812f062c018)
![QQ截图20240603123625](https://github.com/reobf/Programmable-Hatches-Mod/assets/90818327/4d5599f6-f3dc-4d8e-8965-eed5de8423e2)
![QQ截图20240603123601](https://github.com/reobf/Programmable-Hatches-Mod/assets/90818327/d3f16b7b-ab82-4cf3-927c-6f32e8b5e268)
如图所示，下单检测不到提供器的新版电路。对于手动放进去的，开了替换可以检测，关闭替换检测不到。如果依然使用旧版电路则没有问题。

**Comment by reobf** [comment]
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/v0.0.15p1-beta
