### ISSUE TITLE
关于二合一输入镜像的一些问题

### ISSUE THREAD

**Issue by shinyashen** [reobf/Programmable-Hatches-Mod#50]
1. 输入镜像所绑定位置的二合一输入仓在拆除并重新放置后，其中的内容物无法被多方块机器识别处理，此时输入镜像看上去是正确绑定的（复现方法实例：使用精密组装机的普通组装模式处理配方，使用输入镜像作为输入，执行上述的拆除重新放置后，无法执行配方处理）
2. 当输入镜像绑定的是不含缓存的二合一输入仓时，当ae以非阻挡模式向原二合一输入仓发配大量物品时，在配方处理的过程中，有概率（体感为5%左右）出现吞输入物品/流体的情况（猜测原因：发现处理配方的过程中输入仓会出现数量为0的物品/流体，如果此时恰好发配物品/流体，会不会导致此时发配的东西被吞？）

**Comment by reobf** [comment]
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/v0.0.18p5-beta
物品消耗后会留下一个数量为0的物品的问题修了
关于问题1，原版镜像和二合一镜像都是每100tick更新一次绑定目标，或许是还没到100tick？此时右键二合一镜像，是否能打开原二合一的GUI?（新版 二合一镜像可以 和 原版镜像 一样 在waila中显示绑定对象的名称或“not linked”，以这个为准）
关于问题2，数量0物品bug修了，但是吞物品bug没有复现 。不知道有没有修顺带修了

**Comment by shinyashen** [comment]
回复：
1. 应该能确认超过100tick了，能打开GUI且物品看上去是正确对应的，但是机器没有工作，尝试重新绑定后机器立即工作了；
2. 该问题在这个新版本发布之前通过更换为进阶缓冲仓之后似乎就没有出现这个情况了，然后更换过程中出现了问题1(

**Comment by reobf** [comment]
> 回复：
> 
> 1. 应该能确认超过100tick了，能打开GUI且物品看上去是正确对应的，但是机器没有工作，尝试重新绑定后机器立即工作了；
> 2. 该问题在这个新版本发布之前通过更换为进阶缓冲仓之后似乎就没有出现这个情况了，然后更换过程中出现了问题1(

如果再出现问题 求log或者存档

**Comment by shinyashen** [comment]
好的，那issue我先关闭了，有相关问题再reopen吧
