### ISSUE TITLE
me数据访问仓放下就崩溃

### ISSUE THREAD

**Issue by xyhzds** [reobf/Programmable-Hatches-Mod#53]
me数据访问仓放下就崩溃，2.6.1，在花园放的

**Comment by xyhzds** [comment]
就是单纯放下来，未进行任何操作，秒崩

**Comment by reobf** [comment]
有crashreport 或者log吗

**Comment by reobf** [comment]
我的问题... 找到问题修了 就不推版本号了
更新release文件了 重新下载一次吧

**Comment by reobf** [comment]
> 就是单纯放下来，未进行任何操作，秒崩

我的问题... 找到问题修了 就不推版本号了
更新release文件了 重新下载一次吧

**Comment by xyhzds** [comment]
okok
