### ISSUE TITLE
me量子缸bug

### ISSUE THREAD

**Issue by fbjh** [reobf/Programmable-Hatches-Mod#54]
![屏幕截图(3)](https://github.com/user-attachments/assets/b1b29a4b-4799-4b01-8f86-22c88950f50e)

如图所示，me量子缸无法解包流体单元，还有一个不知道是不是bug，me量子缸无法手动放物品只能用管道输入

**Comment by reobf** [comment]
![2024-08-18_02 49 04](https://github.com/user-attachments/assets/d4701747-bb44-4bcf-88d8-1194b1121ebc)
实际上  解包的是这个AE2FC“流体封包”
无法手动放是因为 只有AE2FC“流体封包”能被放进去 ，管道能输入其它物品反而是疏忽...

这个奇怪的设计本来是配合装配线自动化用的，但是个人感觉不太好用所以放弃了
未来的更新可能会换成更有用的功能（比如流体单元交互）

**Comment by fbjh** [comment]
我还发现他无法被管道输入流体

**Comment by reobf** [comment]
> 我还发现他无法被管道输入流体

现在可以处理单元了，空的流体容器会被通过ME网络送回
也可以连管道

https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/v0.0.18p9-beta

**Comment by fbjh** [comment]
感谢



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月18日 15:43 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [reobf/Programmable-Hatches-Mod] me量子缸bug (Issue #54) |

我还发现他无法被管道输入流体

现在可以处理单元了，空的流体容器会被通过ME网络送回
也可以连管道

https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/v0.0.18p9-beta

**Comment by fbjh** [comment]
显示小bug，18P9版本，me量子缸和me量子箱连接ae时，在ae上无法看到数量的变动，比如有一个1s/个的泥土产线，存入进me量子箱，ae里面看只显示上次打开me箱的数量不会发生变化，除非手动从ae里拿出来再放进去,试了下普通的缸和箱不会有这个问题

**Comment by reobf** [comment]
> 显示小bug，18P9版本，me量子缸和me量子箱连接ae时，在ae上无法看到数量的变动，比如有一个1s/个的泥土产线，存入进me量子箱，ae里面看只显示上次打开me箱的数量不会发生变化，除非手动与ae交互时才会刷新,试了下普通的缸和箱不会有这个问题

应该修了 试试看吧
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/v0.0.18p10-beta
