### ISSUE TITLE
Me数据访问仓连接表现奇怪

### ISSUE THREAD

**Issue by P0lar1z2** [reobf/Programmable-Hatches-Mod#55]
v0.0.18p11-beta
me数据访问仓
![image](https://github.com/user-attachments/assets/c4ff63c6-63b8-4449-a1fd-82518ab1f86c)
跨区块连接有问题
是否允许所有面连接

**Comment by reobf** [comment]
修了  应该是因为扳手扭了后没有及时更新连接方向
和跨区块无关
一个装配线一个就够了 所以感觉没有必要支持 所有面连接

https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/v0.0.18p12-beta

**Comment by P0lar1z2** [comment]
那就是了 我以为是不支持跨区快 但是支持其他面
