### ISSUE TITLE
[BUG] ME流体库存升级无法标记流体

### ISSUE THREAD

**Issue by sakarie9** [reobf/Programmable-Hatches-Mod#56]
![image](https://github.com/user-attachments/assets/6335e093-f601-4d23-8139-19b79d8c8e42)

![image](https://github.com/user-attachments/assets/f9a1cb25-fb7d-4675-b968-b5d12f17feca)

在之前的版本（大概是v0.0.18p7？）工作正常，升级到p12后无法标记。在之前版本已经标记的正常工作的新版也不工作了

**Comment by reobf** [comment]
未能复现
![2024-08-21_23 30 36](https://github.com/user-attachments/assets/287613bc-ad4a-463b-8c86-f22182d4e0ed)

用什么流体容器标记？nei书签还是实体物品？
是点了没反应 还是闪一下立刻消失？
能提供log吗？ 
能提供存档吗？
GTNH版本？是否自行升级过mod？

**Comment by sakarie9** [comment]
理解了，原来是不能用书签标记流体

**Comment by reobf** [comment]
> 理解了，原来是不能用书签标记流体

试了一下 好像是NEI的书签拖物品到悬浮窗的BUG
书签物品如果点击位置背后有其它物品槽 就会认为你是想点击背后那个槽位
所以解决方法是把悬浮窗拖到两边（和主窗口不重叠）再用书签功能
这个BUG估计修不了
