### ISSUE TITLE
覆盖版接口开阻挡投料有点问题

### ISSUE THREAD

**Issue by NNNNMMMMIIII** [reobf/Programmable-Hatches-Mod#64]
投料有时候只有第3个格子材料，第二格子的材料不知道去哪里了，还有连续投料时候的阻挡模式，像是只检测第一第二的有没有东西，第三格子有东西也一样会投料

**Comment by reobf** [comment]
未能复现...
mod版本？整合包版本？
样板内容？贴的什么仓？

**Comment by reobf** [comment]
试试这个吧 重构了一下代码 虽然不知道是什么原因 也不知道能不能解决这个问题...
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/v0.0.18p22-beta

**Comment by NNNNMMMMIIII** [comment]
18P20版本，不过前几个版本都有这问题，GTNH261，二合一和多流体仓都有这问题，比如说烧一个钢锭的配方没问题，其他配方也不可能用到煤粉，但实际会出现有东西剩在输入总线里面，就像图片那样，工业搅拌机和合金冶炼炉这2个也是高概率出问题的
![屏幕截图 2024-09-10 155716](https://github.com/user-attachments/assets/0e75af44-00eb-4776-947e-1a0083f5cb30)
![屏幕截图 2024-09-10 155817](https://github.com/user-attachments/assets/4b2b3b13-603f-463d-9b64-9ea882f52046)

**Comment by NNNNMMMMIIII** [comment]
阻挡问题好像是第二格东西一消失马上就投料，有时候完全不管第三格有没有东西的

**Comment by NNNNMMMMIIII** [comment]
分享文件：3
链接：https://pan.xunlei.com/s/VO6QIanAiK9oy2hSxHpumK5hA1?pwd=dhuk#
额外模组 
Twist Space Technolgy Mod
Programmable Hatch Mod
AE2 Thing

**Comment by reobf** [comment]
不好意思能打个压缩包吗...
它只允许一个个文件下载

**Comment by NNNNMMMMIIII** [comment]
链接: https://pan.baidu.com/s/1FI1K_e83KiVFEiupbELceQ?pwd=djg7 提取码: djg7

**Comment by reobf** [comment]
能说一下出问题前具体做了什么操作吗
p20 p22 均未能在存档复现

**Comment by NNNNMMMMIIII** [comment]
很难复现，之前做9合一时候合金冶炼炉莫名多出了几个铬粉，做ME存储输入总线时候里面HV的输入总线变成输出总线，看配方没问题都是有虚拟电路板的，然后看机器里面的虚拟电路突然变成2了，全部都是在上了IV换成大机器才出问题，小机器没问题

**Comment by NNNNMMMMIIII** [comment]
现在出BUG了，给你看看截图，版本18P20
![屏幕截图 2024-09-11 160600](https://github.com/user-attachments/assets/1ed04d0c-fac7-4312-b06b-9bffc812ad36)
![屏幕截图 2024-09-11 160639](https://github.com/user-attachments/assets/cd0c8768-08a6-493d-a064-a87a05ab1dd9)
![屏幕截图 2024-09-11 160706](https://github.com/user-attachments/assets/58a95633-7ab8-49c2-a46a-0c844898c2a1)

**Comment by NNNNMMMMIIII** [comment]
说错是18P21

**Comment by reobf** [comment]
左上角按钮是手动关的吗 如果不是能不能提供一下log

**Comment by NNNNMMMMIIII** [comment]
不是，默认配置没改就直接放下来的

**Comment by NNNNMMMMIIII** [comment]
现在还发现其他奇妙BUG，比如我点虚拟电路槽然后我物品少了。比如说点一下7号虚拟电路板然后我的无线接入器少了一个
![屏幕截图 2024-09-11 161842](https://github.com/user-attachments/assets/bdd347e1-0804-4520-8966-ac5a30aeb8d6)
![屏幕截图 2024-09-11 162116](https://github.com/user-attachments/assets/31c24288-b0ca-4dcf-ba1b-85e0522085ac)

**Comment by NNNNMMMMIIII** [comment]
通过网盘分享的文件：2024-09-11-2.log.gz
链接: https://pan.baidu.com/s/1FB8ZOVVzuw7F11D_2OPenA?pwd=ter6 提取码: ter6

**Comment by reobf** [comment]
大概知道问题在哪里了...
装着覆盖板拆卸的话 物品会带有 仅含覆盖板的nbt 
这个nbt缺少机器本身的数据 读取时就会错误
先不要带板拆机吧 拿撬棍先敲下来再拆机

**Comment by NNNNMMMMIIII** [comment]
确实，刚刚才把化反换位置才出问题的，之前没这问题
不过物品消失怎么回事，点了几下吃了我几个无线接入器

**Comment by reobf** [comment]
消失时的log也在网盘文件里吗

**Comment by NNNNMMMMIIII** [comment]
嗯，我是先退了在发你log

**Comment by reobf** [comment]
可能是因为覆盖版的me网络数据也被保存在掉落的机器里了
实际放下去以后，位置变了 加载的数据却是原来位置的...

GT5这个处理的流程就很奇怪 
不装覆盖版机器配置拆了丢失，装了机器配置部分保存 
放机器物品放下时 读取物品保存的数据 和 读取存档 强行走同一个方法...
大电装拆机保存铭刻电路把维护状态也保存了 再放不用修 大概也是这个原因

看看能不能解决吧

**Comment by reobf** [comment]
试试
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/v0.0.18p23-beta
带板拆机器 放置后板子会掉落，需要重写安装

**Comment by reobf** [comment]
> 现在还发现其他奇妙BUG，比如我点虚拟电路槽然后我物品少了。比如说点一下7号虚拟电路板然后我的无线接入器少了一个 ![屏幕截图 2024-09-11 161842](https://private-user-images.githubusercontent.com/164090019/366362751-bdd347e1-0804-4520-8966-ac5a30aeb8d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMzQwNzMsIm5iZiI6MTcyNjEzMzc3MywicGF0aCI6Ii8xNjQwOTAwMTkvMzY2MzYyNzUxLWJkZDM0N2UxLTA4MDQtNDUyMC04OTY2LWFjNWEzMGFlYjhkNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMlQwOTM2MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDY4ZjQwZmYwYzI5ZWRlOGMxZDJmZTFiZWYxMzA0YTQzZmI1ODcxZjRhOTJlOGFjMzVmODkwNDg2MjkwZmZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3mW4ikTUfsXjO7brzW9xFpjTDKn05aF2WU46Axp-q4I) ![屏幕截图 2024-09-11 162116](https://private-user-images.githubusercontent.com/164090019/366362771-31c24288-b0ca-4dcf-ba1b-85e0522085ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMzQwNzMsIm5iZiI6MTcyNjEzMzc3MywicGF0aCI6Ii8xNjQwOTAwMTkvMzY2MzYyNzcxLTMxYzI0Mjg4LWIwY2EtNGRjZi1iYTFiLTg1ZTA1MjIwODVhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMlQwOTM2MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNzcyMzBlMjNhMWYyYmRkNjhhYmQwNGFjMjgzMWRiZGY0M2FmMDkyMDZmOWZmOTc0OGNjNzA4NjEwNDZlODE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Gg8BfcBv9CSXHssemFbCaBHzFbVjIhKGv91hlrGktwQ)

大概是因为带板拆机放了就会触发读取nbt
但是这个nbt除了覆盖版数据 不含机器数据
mc的nbt读取规则就是如果缺tag不报错 直接按0处理
估计是槽位被设为0，映射到背包里了
