### ISSUE TITLE
这BUG真的烦人

### ISSUE THREAD

**Issue by NNNNMMMMIIII** [reobf/Programmable-Hatches-Mod#65]
![屏幕截图 2024-09-23 180204](https://github.com/user-attachments/assets/61936a17-a539-4233-b43d-9ea6481c8cc3)
但凡看到虚拟电路板的数量叠起来就知道肯定会被吞材料，版本261，18P27

**Comment by reobf** [comment]
使用二合一镜像了吗
什么机器
剩下的两个物品是数量为0一点就消失那种吗
带覆盖板板拆过机吗

**Comment by NNNNMMMMIIII** [comment]
普通P2P二合一也一样出问题，阵列里面是组装机，化反和高炉都出过问题，没拆过机
![屏幕截图 2024-09-23 045517](https://github.com/user-attachments/assets/13007962-153e-404b-8cbc-a3b53040ef2e)
![屏幕截图 2024-09-23 045517](https://github.com/user-attachments/assets/09aeb43f-4415-4109-8f9e-8403c136fe51)
![屏幕截图 2024-09-23 045505](https://github.com/user-attachments/assets/014d5f96-d68a-44ad-b3ee-5d380de67f7b)
![屏幕截图 2024-09-23 045505](https://github.com/user-attachments/assets/4c59e87e-ba15-4bc5-9a0f-92af4d649319)
![屏幕截图 2024-09-23 045454](https://github.com/user-attachments/assets/bc181c07-ab74-4df7-beca-3f0ca67ba5a0)
![屏幕截图 2024-09-23 045443](https://github.com/user-attachments/assets/0692e869-4563-497f-b4da-05a8863ada1c)
![屏幕截图 2024-09-23 044435](https://github.com/user-attachments/assets/f8ffefbd-f534-4447-99bc-63ab331dcd43)

**Comment by reobf** [comment]
...有办法稳定复现吗

**Comment by reobf** [comment]
尽管尝试修过...但之前已经带板拆过的仓 上面的接口可能依然保留了错误的数据
或许需要再重装一次吧

**Comment by NNNNMMMMIIII** [comment]
不知道，但这2次出现都是长时间挂机或者跑图才出问题的，第一次是多次TP其他星期挖矿，第二次是刚下单就去罗斯128跑图，然后回来发现才出问题

**Comment by reobf** [comment]
多谢 发现问题了 大概就是gt自带的物品栏 保存数量超过127就会溢出有关吧明天应该能修好

**Comment by reobf** [comment]
能复现 修了
之前我假设 GT保存物品栏的时候 会为空气也保存一个空数据...
但实际上GT是直接额外加了一个nbt标签指定位置，跳过空气 不依赖nbt标签顺序
所以S/L之后数量会错位
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/v0.0.19p1-beta
