### ISSUE TITLE
[反馈/建议]在nei中合并标签

### ISSUE THREAD

**Issue by PinkYuDeer** [reobf/Programmable-Hatches-Mod#66]
![image](https://github.com/user-attachments/assets/134c1daf-8e39-44a9-bfc5-76ff7b0bb436)
在最新版2.7.0中，其他输入总线输出总线在nei中已经以组的形式呈现，可编程输入仓的这些方块实际上也是一组不同电压的方块。是否可以在nei中合并显示？（我理解这个合并行为也有可能是nei-gtnh版的行为，不是nei之外的mod控制的，但是我不确定是否真的不由自定义模组控制，来碰个运气。）

**Comment by reobf** [comment]
![2024-09-25_22 44 48](https://github.com/user-attachments/assets/5417ba92-6223-491b-9a7d-ef89fead0d80)
其实GTNH都是手动写配置分类的... 
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/a1da6660e82a170f6e01903eba2a15d957fe6fad/config/NEI/collapsibleitems.cfg
可能会支持吧 主要是NEI那边api还不稳定（实际上根本没有向外暴露 折叠相关的接口）只能改NEI配置文件 
图片是用mixin插入的分组逻辑

**Comment by reobf** [comment]
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/v0.0.19p3-GTNH270-beta
![2024-09-26_23 30 53](https://github.com/user-attachments/assets/c3f975fd-0e39-49f5-af92-4d7bfe478645)
折叠了一些我觉得算同类的仓
