### ISSUE TITLE
ME量子箱的在收到合成的产物时，似乎不被判断为ME网络收到了产物，导致合成无法完成

### ISSUE THREAD

**Issue by Armelia-William** [reobf/Programmable-Hatches-Mod#67]
RT，
实际上产物已经合成完毕了
![2024-09-27_11 57 44](https://github.com/user-attachments/assets/a33bb4b9-b8e7-422d-8dab-f22f2c75b936)

**Comment by reobf** [comment]
未能复现
如果是直接输出到ME箱子，那确实不行
ME箱=存储总线+超级箱
往一个贴存储总线的原版箱子输入物品，也是检测不到的 这是AE原版特性

**Comment by reobf** [comment]
ME超级箱 开启粘性模式 并标记过滤
就能保证同类物品优先进入此容器
![1727410935955](https://github.com/user-attachments/assets/cca88f61-653b-4367-b302-f20ec9ad7156)

**Comment by Armelia-William** [comment]
> 未能复现 如果是直接输出到ME箱子，那确实不行 ME箱=存储总线+超级箱 往一个贴存储总线的原版箱子输入物品，也是检测不到的 这是AE原版特性
不好意思，我可能没表达清楚，物品是直接通过ME线缆进入ME量子箱的，如图1和2，如果我使用超级缸+存储总线，合成完毕的物品会自动关闭订单，但是图3和图4的ME量子箱会卡着CPU，但实际物品已经成功进入容器了。
![1](https://github.com/user-attachments/assets/e4216cfb-1ab8-4746-af42-c3af17cfe696)
![2](https://github.com/user-attachments/assets/fac1406d-f312-4525-87b8-bcdd46cd999d)
![3](https://github.com/user-attachments/assets/1a047571-1d34-41c5-880f-384865353e8e)
![4](https://github.com/user-attachments/assets/00394d6d-347b-4314-9c80-ff7a0bbdd856)

**Comment by reobf** [comment]
机器输出用的是me输出总线还是普通的
整合包版本
mod版本
如果存档不大可以考虑上传一下(传到网盘等)

**Comment by Armelia-William** [comment]
> 机器输出用的是me输出总线还是普通的 整合包版本 mod版本 如果存档不大可以考虑上传一下（传到网盘等）
机器输出用的是ME输出总线
整合包版本2.61
programmablehatches-0.0.19p2
appliedenergistics2-rv3-beta-357-GTNH

**Comment by reobf** [comment]
有调整过超级箱优先级吗？ 尤其是调到2.1g最大值可能会有问题
网络除了me箱还有其他存储吗

**Comment by Armelia-William** [comment]
> 有调整过超级箱优先级吗？ 尤其是调到2.1g最大值可能会有问题 网络除了me箱还有其他存储吗

量子箱优先级是1000,存储是连在ME主网络上的，存储太多了。。。。，但是物品确实能成功进去，只是CPU不知道为什么卡住了
存档上传好了，https://pan.baidu.com/s/1uHp6AuouERJ64aVY6uxx3w?pwd=14ub 提取码: 14ub

**Comment by reobf** [comment]
多谢 现在手头没电脑....可能需要等

**Comment by Armelia-William** [comment]
> 多谢 现在手头没电脑....可能需要等
嗯摁，没事没事，不是什么恶性bug，另外类似的，在连续合成的时候，于是CPU也无法识别到接收到了物品，参与下一步晶体电路合成的时候不会被CPU给拦截走，会直接进入ME超级箱。
![image](https://github.com/user-attachments/assets/dd140bb8-4363-438e-b076-6748849a4c6a)

**Comment by reobf** [comment]
复现了 不是我的问题 是AE的粘性模式有bug
[请移步](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/545)

**Comment by Armelia-William** [comment]
> 复现了 不是我的问题 是AE的粘性模式有bug [GTNewHorizons/Applied-Energistics-2-Unofficial#545](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/545)

谢谢你
