### ISSUE TITLE
Pattern

### ISSUE THREAD

**Issue by TimberDimber** [reobf/Programmable-Hatches-Mod#68]
Is there any way to make it so that when making pattern, "programmable chips/shapes/lenses" are automatically added to the recipe, rather than having to add them manually?

**Comment by reobf** [comment]
Yes.
Carry this item in your inventory and the job is done automatically.
![toolkit0](https://github.com/user-attachments/assets/b438bfb3-9e5a-490d-a720-b286ea2afd61)
its called something like 'Programming Toolkit'

**Comment by reobf** [comment]
should switch to mode 2/3 first, as described in tooltips
