### ISSUE TITLE
Voiding mode

### ISSUE THREAD

**Issue by TimberDimber** [reobf/Programmable-Hatches-Mod#70]
Is it possible to enable overflow voiding mod in ME Chest/Tank?

**Comment by reobf** [comment]
Currently no.
Maybe in the next release, you might leave this issue open untill it's implemented.

**Comment by reobf** [comment]
done https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/v0.0.19p7-beta

**Comment by TimberDimber** [comment]
Tnx <3
This one too? https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/v0.0.19p7-GTNH270-beta

**Comment by reobf** [comment]
Yes they are basically the same thing, but with some different naming.
Because GTNH dev changed a lot of naming in 2.7.0.
