### ISSUE TITLE
Assline Decoy Stocking 

### ISSUE THREAD

**Issue by TimberDimber** [reobf/Programmable-Hatches-Mod#74]
Can I see some example or get a hint on how to use it?
I tried to figure it out myself, but in any variations it does not distribute items to input buses .-.

**Comment by reobf** [comment]
The design of Assline is to assume all ME input buses are in the same ME storage.
But if 16 ME input buses uses different ME storage, the Assline will stuck if recipe contains duplicated items.
This hatch is to solve this problem
![2024-10-03_21 57 46](https://github.com/user-attachments/assets/06650ea4-82b4-4df7-b291-91bda2137879)
Useless if you do not use 16 independent ME network to supply items to Assline, I guess.

**Comment by reobf** [comment]
Assline will check the first item in ME Bus, and extract items from the **LAST** ME Bus that contains this item.
This will not be a problem if all ME input buses are in the same ME storage, but if not it screws anything up. 
Maybe GTNH dev assumes that all player will use one Assline dedicated for one signle recipe, if they are useing ME Bus.

**Comment by reobf** [comment]
The bus collects all items (via storage bus) in 16 ME networks' storage to trick the Assline to start(that why it's called a decoy).
And try to extract items evenly from these 16 ME networks' storage because Assline will only extract items from the LAST ME Bus in this case.

**Comment by reobf** [comment]
Well the tooltips are a little ambigous, will improve it somtime.

**Comment by TimberDimber** [comment]
![image](https://github.com/user-attachments/assets/b66069d4-ae96-424b-9608-3c86a47c33da)
Am I miss something?

**Comment by TimberDimber** [comment]
![image](https://github.com/user-attachments/assets/93ef72b4-0c2e-40dc-81cd-f3abc29ac78c)
For example, I try to do this one

**Comment by TimberDimber** [comment]
![image](https://github.com/user-attachments/assets/ecbfe84e-d134-49bf-bcbe-870851abb561)
If use 63 types card in last one chest

**Comment by reobf** [comment]
![2024-10-06_18 00 01](https://github.com/user-attachments/assets/5a5d5931-c5ad-4bdc-865b-7606e4905a80)

**Comment by reobf** [comment]
It's inteded to work with a machine called 'Electrical Ingridient Distributor' of this mod
which is bad-documented...

**Comment by TimberDimber** [comment]
I really don't understand, where I miss something. Can you share save-file, where it works?

**Comment by reobf** [comment]
[nw.zip](https://github.com/user-attachments/files/17269098/nw.zip)
sure

**Comment by reobf** [comment]
![2024-10-06_19 26 10](https://github.com/user-attachments/assets/c852f999-ffc4-436c-9948-e97cb460d6b8)
its here
submit crafting tasks on Terminal to see how it works

**Comment by TimberDimber** [comment]
Okay, I see... but somehow it works even without decoy bus. 
And if I want to make several lines working in parallel, I need to build a similar setup for each of them?

**Comment by reobf** [comment]
Are you sure?
Did all tasks finish?

**Comment by reobf** [comment]
It's up to you.
Or you can just extend the ME Cable and make a new Assline sharing the ME network.

**Comment by TimberDimber** [comment]
Never mind, it only sometimes works, more often it doesn’t.

Thank you very much for taking the time to show me how it works.
I think the tooltip should include a line about use it in combination with distributor

**Comment by TimberDimber** [comment]
Will it work fine with universal aal's?

**Comment by reobf** [comment]
what's it short for

**Comment by TimberDimber** [comment]
https://wiki.gtnewhorizons.com/wiki/Advanced_Assembly_Line#Automation

**Comment by reobf** [comment]
I use advanced Assline in that game savefile.
But I don't see 'universal '?

**Comment by reobf** [comment]
"Duplicate items that are full stacks also need to be renamed."
That's the bug. And the decoy bus is just a way to solve it.

**Comment by reobf** [comment]
I'm pretty sure the Assline will screw it up if you don't rename it.

**Comment by TimberDimber** [comment]
Oh, I didn't even notice that there was an advanced one there.
In ru-segment, we call it universal when one aal can perform any recipes without conflicts. Actually, that's it. I'll try to use this scheme on my base in the near future, using the example of motors with 7 identical fine wires.
Thanks again for the explanation, and it's quite possible that this should be formatted as a short guide on the mod's wiki page.

**Comment by reobf** [comment]
Oh, I get it now.

**Comment by TimberDimber** [comment]
![image](https://github.com/user-attachments/assets/14f7ae97-3068-40b2-8ab0-66ad838c10b3)
![image](https://github.com/user-attachments/assets/d5e2ac30-3781-4f04-8b83-8e2cd154af56)
![image](https://github.com/user-attachments/assets/86e5c025-06e2-4f5b-ab1c-696af369248e)
![image](https://github.com/user-attachments/assets/ab2f8578-1e91-4574-9e0f-b823cabd1b07)
![image](https://github.com/user-attachments/assets/185a395b-d973-49a0-b4bb-8887944844c1)
![image](https://github.com/user-attachments/assets/411c40a1-afcd-4b46-a091-fe20c6d91f0d)
![image](https://github.com/user-attachments/assets/c96c3164-f463-4273-92e1-ce1b76356cad)

**Comment by TimberDimber** [comment]
Any tips or recommendations for usage if crafting requires 16 ingredients (like in DTPF)?

![image](https://github.com/user-attachments/assets/14e74c17-b871-4e16-b712-ab54773f60f9)
![image](https://github.com/user-attachments/assets/e1d9447c-3dd2-42c8-b8ef-53c2c354084d)
![image](https://github.com/user-attachments/assets/34bf3324-3426-4828-b0f8-ddce2a71d993)
