### ISSUE TITLE
超级流体二合一输入仓与描述不符

### ISSUE THREAD

**Issue by haliludaxuanfeng** [reobf/Programmable-Hatches-Mod#76]
![QQ20241010-035415](https://github.com/user-attachments/assets/0dce6b7b-eadc-4984-930e-072b9c223bfc)
![image](https://github.com/user-attachments/assets/d4ba540a-5cd8-420c-bf09-37b8503eeea9)
描述有16格实际上只有4格

**Comment by reobf** [comment]
tooltips描述有误...下个版本修正
这东西本来是给等离子搅拌机用特供的
结果其它仓也buff过了这东西其实也没什么特别优势了

**Comment by haliludaxuanfeng** [comment]
- [ ]
