### ISSUE TITLE
电力分拣神奇BUG

### ISSUE THREAD

**Issue by NNNNMMMMIIII** [reobf/Programmable-Hatches-Mod#79]
经常出现只转移一小点就卡主了，之前19P7还没遇到，更新后一上来就出现这情况，现在是19P9版本 GTNH270
![屏幕截图 2024-10-11 155053](https://github.com/user-attachments/assets/76f190e4-9974-492f-bfd5-bd2057371fcb)
![屏幕截图 2024-10-11 155022](https://github.com/user-attachments/assets/4cabf100-a6a7-464a-945d-abdab9087738)
![屏幕截图 2024-10-11 155008](https://github.com/user-attachments/assets/eff10315-3adf-4d96-90fe-092a846207c7)
![屏幕截图 2024-10-11 155003](https://github.com/user-attachments/assets/629dba83-81f2-4783-a43a-47575464f1ac)

**Comment by reobf** [comment]
能给个存档吗

**Comment by NNNNMMMMIIII** [comment]
通过网盘分享的文件：123.zip
链接: https://pan.baidu.com/s/1EUDwalsWKQgKD5BUACRjLQ?pwd=weka 提取码: weka
早上更新时候一上来就发现的，当时以为是加载没起来等一下就好，后来挂机做东西看到电路板卡主不动又出现这问题，两次都是MV电路板出的问题，样板也就64倍,流体才9216，不存在卡流体情况，我把装配线的流体拿出来后电力分拣里面的流体和上面的图一样卡在哪里不过去，后面我看着他干活时候流体是正常过去的，就算阻挡模式也一样过去
![屏幕截图 2024-10-11 103715](https://github.com/user-attachments/assets/422e83a1-352d-47fe-8f25-5f7ccf64ba98)

**Comment by NNNNMMMMIIII** [comment]
当时我全部看过了，ME输出总线里面没有缓存任何东西，只有投料那点锡

**Comment by reobf** [comment]
有当时的log吗

”我把装配线的流体拿出来后电力分拣里面的流体和上面的图一样卡在哪里不过去“
为什么要拿装配线流体 因为装配线不工作吗 装配线的物品输入没有正常运行吗（me驱动器并没有收到物品？）

阻挡模式是绕过ME总线缓存直接塞网络的
所以可能是是以非阻挡模式跑了一次（可能是bug）

**Comment by reobf** [comment]
此外组装模式的大电装应该是直接支持二合一无序输入的吧...？

**Comment by NNNNMMMMIIII** [comment]
当时我看了一圈，物品全部进去ME驱动器就剩下流体，然而流体莫名奇妙只进去64L，然后投料口有4000L不进去，把流体拿出来再重启电力分配还是卡在那里不进装配线里，截图歪了，输入仓是HV

**Comment by NNNNMMMMIIII** [comment]
当时我看了一圈，物品全部进去ME驱动器就剩下流体，然而流体莫名奇妙只进去64L，然后投料口有4000L不进去，把流体拿出来再重启电力分配还是卡在那里不进装配线里，截图歪了，输入仓是HV

**Comment by NNNNMMMMIIII** [comment]
大电装不用顺序，当时我看过每一个硬盘就有东西，就剩下流体不进去

**Comment by NNNNMMMMIIII** [comment]
![屏幕截图 2024-10-11 200243](https://github.com/user-attachments/assets/8631e0d7-be46-42bd-9273-497bd7d992ae)

**Comment by reobf** [comment]
有当时的log 吗

**Comment by reobf** [comment]
还有可能就是当时没开阻挡模式

**Comment by NNNNMMMMIIII** [comment]
没有当时LOG,阻挡模式一直开的，19p7用了6天也没见过这问题，19p9一更新就出现了
![屏幕截图 2024-10-12 042747](https://github.com/user-attachments/assets/4ed8c715-7d53-417b-a919-01e381887d47)

**Comment by reobf** [comment]
但问题是这两个版本之间我根本没改它的功能...
有可能是跨区块的问题...（末尾两个框架超了）
修了几个可疑的地方 估计晚上发release 你再看看
最好是 再出问题时候 能提供那个瞬间的存档 会比较有参考性
