### ISSUE TITLE
新版中编程器电路提供器HV可以制造，但是制造需要编程工具箱，编程工具箱需要EV才能制造

### ISSUE THREAD

**Issue by liansishen** [reobf/Programmable-Hatches-Mod#8]
新版中编程器电路提供器HV可以制造，但是制造需要编程工具箱，编程工具箱需要EV才能制造

**Comment by liansishen** [comment]
补充一点：制造覆盖版需要熔融钨钢，钨钢也需要EV

**Comment by reobf** [comment]
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/v0.0.15p2-beta
工具箱降到hv
覆盖版可选熔融不锈钢代替熔融钨钢减产到一半
