### ISSUE TITLE
不知道算不算BUG，物品数量太多缓存会出问题

### ISSUE THREAD

**Issue by NNNNMMMMIIII** [reobf/Programmable-Hatches-Mod#83]
版本270,19P12
做东西发现只有化学浸洗才有的问题，而且非常容量卡主，样板写了8倍，投料为什么会出现7呢
![屏幕截图 2024-10-21 053714](https://github.com/user-attachments/assets/4bb5c4fa-f947-48e1-a106-509398a4b505)
![屏幕截图 2024-10-21 053601](https://github.com/user-attachments/assets/57f78822-bbdf-4f83-9ce6-7796b4b0f681)
![屏幕截图 2024-10-21 053546](https://github.com/user-attachments/assets/9314645d-470c-4112-b61e-e58e303958a2)
![屏幕截图 2024-10-21 053533](https://github.com/user-attachments/assets/a2cecb0b-1dc8-4791-92a3-ed7ed206bb64)

**Comment by reobf** [comment]
外面1544碳纤维 223232 树脂
里面7碳纤维       112 树脂
(223232+112)/(1544+7)=144 =144比1
1544+7=1551份材料没有吞

原因是没开阻挡（或者阻挡失效？）
总共3328份
共479232（3328*144）mb流体 3328物品
首次进去了 256000mb流体（外缓限制）和1784物品（无法注入流体 二合一因为最多缓存一单，卡住）
做了1777份，剩下
256000-1777*144=112
1784-1777=7
这就是内部剩下的数量

外部第二次发配剩余479232-256000=223232mb流体留在外面
以及3328-1784=1544 物品也对的上（192*7+128+64+8=1544）

**Comment by reobf** [comment]
所以如果阻挡没卡，那么打开（并行足够，有特殊处理，能在2tick发配所有材料不会有性能损失）
如果打开但没挡住，应该是不过，请尝试是否能稳定复现（阻挡失效的bug）
除了上面的替代解决方案：
1.用非缓冲版本，这样就内缓就不会出现做不完的非整数原料
2.打开“允许流体流入不同流体槽”按钮，这样树脂会进入第二个流体格子而不是被第一格256，000mb限制住

**Comment by reobf** [comment]
看到你的截图覆盖板开阻挡了
但是实际上似乎并没有挡住
如果这是个bug且能复现
麻烦请发一下存档 谢谢

**Comment by reobf** [comment]
不能稳定复现很难排查...
可能是区块加载时由于什么原因阻挡模式没正常生效..
issue就先开着吧

**Comment by NNNNMMMMIIII** [comment]
复现成功，100%触发

**Comment by NNNNMMMMIIII** [comment]
![屏幕截图 2024-10-25 043840](https://github.com/user-attachments/assets/2727268c-a5cb-44a2-a1b2-06ed962d30a7)
![屏幕截图 2024-10-25 043830](https://github.com/user-attachments/assets/296e7fbb-a0e7-4d39-94ce-46775f4df4bc)
![屏幕截图 2024-10-25 043320](https://github.com/user-attachments/assets/45423e80-79c3-456c-a978-f7fdc815f9f5)
![屏幕截图 2024-10-25 043306](https://github.com/user-attachments/assets/d4481f8c-fe8f-4597-af31-c5f90740e57a)
![屏幕截图 2024-10-25 043249](https://github.com/user-attachments/assets/79f37eec-816d-4cdd-9281-c5a487d5ddc9)

**Comment by NNNNMMMMIIII** [comment]
也就是说投料单格超过768就有可能造成缓存数目不对等，然后发生数量不对导致后续物品进不去缓存

**Comment by reobf** [comment]
![2024-11-13_18 34 54](https://github.com/user-attachments/assets/8f95c66a-39ee-471d-ba6b-5fc24cb00906)

**Comment by reobf** [comment]
@NNNNMMMMIIII
