### ISSUE TITLE
270 beta-3蓝图一点电力分拣直接崩溃

### ISSUE THREAD

**Issue by NNNNMMMMIIII** [reobf/Programmable-Hatches-Mod#84]
就普通右键电力分拣出事，点普通多方块机器没事，崩溃显示是蓝图的模组，不知道那个的问题

**Comment by reobf** [comment]
GTNH dev乱改api导致的
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/0.0.19p16-beta
