### ISSUE TITLE
电力分拣机的几个问题

### ISSUE THREAD

**Issue by NNNNMMMMIIII** [reobf/Programmable-Hatches-Mod#85]
装配线的每个输入如果采用独立子网络的话那非常庞大工作量而且不好扩展，但是采用主网络的模式就有一个问题，比如说马达配方的3 4格子都是相同的东西，但是电力分拣输出时候3号缓存和4号缓存一样而且优先级更高，会变成4号格子缓存的东西进去3号缓存里面，5号进去4号缓存，造成物品错位，当然也能用普通输出总线来解决，但这也有个问题，就是不能触发阻挡模式，现在想到的解决方法就是需要带优先级的输出总线，只能输出指定的优先级缓存，配合ME超级箱就能做到超简单的搭建方式，比如图片那样
![屏幕截图 2024-10-24 165010](https://github.com/user-attachments/assets/c3a8d082-e2ef-4083-aba2-fcac8b1f8a7e)

**Comment by reobf** [comment]
给ME超级箱交替涂色隔离频道，换me输出总线
每个ME超级箱接一个面板形式的ME接口，然后弄一个主网用16个存储总线（设定不同优先级）访问这些16个ME接口
主网接 用优先级过滤输入的装配线

**Comment by NNNNMMMMIIII** [comment]
大概懂了怎么改，还有ME超级箱子有问题，和当时的精密问题一样，不打开东西不传进去一点开马上传，优先存储总线不能拉取ME箱子，只能拉ME超级箱子和驱动器

**Comment by NNNNMMMMIIII** [comment]
通过输出总线直连ME超级箱子或者存储总线连上M超级箱子都是一样，东西卡在输出总线很久才进去
