### ISSUE TITLE
Problem with Electric Ingredient Distributor

### ISSUE THREAD

**Issue by evgengoldwar** [reobf/Programmable-Hatches-Mod#86]
Blocking button cannot be pressed 

![image](https://github.com/user-attachments/assets/bd5fa486-1800-4132-8eb5-c275f767bf10)

![image](https://github.com/user-attachments/assets/a3b76776-28ad-4c6d-bc92-155ea4811ba0)

![image](https://github.com/user-attachments/assets/11cf4397-f8e8-4773-9e96-6fce6d9f55cb)

Multiblock works but I can't press the Blocking mode button

**Comment by reobf** [comment]
Did you use Yttrium Frame instead of Terbium Frame?
Did you use non-ME Fluid Output Hatch?
How about power button? Can you turn it on?

**Comment by evgengoldwar** [comment]
> Did you use Yttrium Frame(cheap ver. without blocking mode support) instead of Terbium Frame? Did you use non-ME Fluid Output Hatch? How about power button? Can you turn it on?

![image](https://github.com/user-attachments/assets/c038e2a3-b18a-48e3-9e46-aa3b991b99a5)

Oops

I just almost never press shift when viewing the tooltip

**Comment by reobf** [comment]
When you hold more than 1 blueprints
and build it in creative mode, it will use Yttrium Frame.

**Comment by reobf** [comment]
> Maybe it would be better to post without pressing shift?

Did not quite get the point...
What does 'post' mean?

**Comment by evgengoldwar** [comment]
Like this

![image](https://github.com/user-attachments/assets/09eb160d-2450-4f5b-98c9-a67a7343afb4)

**Comment by reobf** [comment]
> @reobf And one more thing - it may be necessary to fix the mod for newer versions of Nightly, when the structure of the tooltip was changed, because in the latest versions there is no tooltip at all. "
> 
> ![image](https://private-user-images.githubusercontent.com/22298720/379838652-8d9f02a7-08dc-4f00-9c3f-7396b091b09e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3ODQ3NjIsIm5iZiI6MTcyOTc4NDQ2MiwicGF0aCI6Ii8yMjI5ODcyMC8zNzk4Mzg2NTItOGQ5ZjAyYTctMDhkYy00ZjAwLTljM2YtNzM5NmIwOTFiMDllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDE1NDEwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkYzRmZjU4OTQ4MzBlODAyNWFhNGM2ZWFlNzA3NGQ3NzBlNWNjOTk0NTY5NWE2NjBmN2U5NmRhZjAwODRmNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7zNDZaN8XyCKXq2No0RO_mzSoE-WGKmDMwXAPZV4Iq4)
> 
> They change this one. ![image](https://private-user-images.githubusercontent.com/22298720/379839063-819ce3d8-02a3-4e0c-a0ac-1358b4cd8051.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3ODQ3NjIsIm5iZiI6MTcyOTc4NDQ2MiwicGF0aCI6Ii8yMjI5ODcyMC8zNzk4MzkwNjMtODE5Y2UzZDgtMDJhMy00ZTBjLWEwYWMtMTM1OGI0Y2Q4MDUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDE1NDEwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxMDQ4M2RlZGUwMDZmM2M0NTU5ZDQ1YTYzMWE2MDk0MGQzZDBhMTRiZjg1YzMzZWI2NmM0YmU3MDA4ZjcwZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.C0NEGnL8jniyO_fY6JU11-5UJCi53duXTvvZCZZnvis)
> 
> Now it's not .toolTipFinisher(ModName) but .toolTipFinisher();

fixed in19p16

**Comment by reobf** [comment]
actually its varargs
String...

**Comment by reobf** [comment]
it's sourcecode level compatible
but not binary compatible

**Comment by reobf** [comment]
They hardly cares about binary compatibility

**Comment by TimberDimber** [comment]
> fixed in19p16

Oh, i miss new one)
