### ISSUE TITLE
Problem with Fluid Input Slave

### ISSUE THREAD

**Issue by evgengoldwar** [reobf/Programmable-Hatches-Mod#87]
Fluid Input Slave does not work in Assembling line
![image](https://github.com/user-attachments/assets/8b2b6ad0-fe82-473f-a26e-5709bdebd98c)

**Comment by TimberDimber** [comment]
Thus, the alternative is either to use a usual fluid stocking and manually specify all possible liquid variants in it, or to use Fluid Input Slave and any kind of dual hatch without buffers, for storing liquid, which seemed to me a logical option.
As another option is to use Remote Input Hatch, but I couldn't find anything to bind it to.

**Comment by reobf** [comment]
Fluid/Item Input Slave maps to the first non-empty buffer.
Fluid Input Slave acts like a Multifluid Hatch.
And when used on Assline, the Assline will only check the **first** slot of Multifluid Hatch.

**Comment by evgengoldwar** [comment]
> So Fluid/Item Input Slave is designed in case some multi-block do not (properly) support Dual Hatch/Buffer. It's not for Assline automation generally speaking...

So Decoy Stocking can't be used before getting Advanced Stocking Input Hatch?

**Comment by reobf** [comment]
Decoy Stocking is to workaround the bug/feature of Assline handling ME inputs.
If you do not use pure ME inputs, Decoy Stocking is pointless.

You can simply use input buses(with sorting mode on) on Assline.
And use Remote Input buses on another Assline to share its inputs.

**Comment by TimberDimber** [comment]
> Decoy Stocking is to workaround the bug/feature of Assline handling ME inputs. If you do not use only ME inputs, Decoy Stocking is pointless.
> 
> You can simply use input buses(with sorting mode on) on Assline. And use Remote Input buses on another Assline to share its inputs.

![image](https://github.com/user-attachments/assets/40f10000-e8ea-435c-b5f7-e84c3e6d81d5)
How to link Remote Input?

**Comment by reobf** [comment]
> > Decoy Stocking is to workaround the bug/feature of Assline handling ME inputs. If you do not use only ME inputs, Decoy Stocking is pointless.
> > You can simply use input buses(with sorting mode on) on Assline. And use Remote Input buses on another Assline to share its inputs.
> 
> ![image](https://private-user-images.githubusercontent.com/22298720/380260421-40f10000-e8ea-435c-b5f7-e84c3e6d81d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NzY0MjMsIm5iZiI6MTcyOTg3NjEyMywicGF0aCI6Ii8yMjI5ODcyMC8zODAyNjA0MjEtNDBmMTAwMDAtZThlYS00MzVjLWI1ZjctZTg0YzNlNmQ4MWQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDE3MDg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhYmU4N2RhOTJiNDVhZTJlN2Q2Yjc0MzM4MjBiMWFlYmE3OTExZWM2MjIwNWMwYjBmMjJjNTBjODhkMWFiMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ziNYo33iR7nq_M0TgwiOmPDIMQCY-PONAcblj3ObFJs) How to link Remote Input?

You got the tricorder, then L-click the Remote Bus

**Comment by TimberDimber** [comment]
As I show - it Link failed

**Comment by TimberDimber** [comment]
https://github.com/user-attachments/assets/e0c9c56f-8ce7-4b98-bd6e-514d33902966

**Comment by reobf** [comment]
> As I show - it Link failed

They changed the index of colour code.
old:----- X: §b923§r Y: §b4§r Z: §b-488§r D: §b0§r -----
new:----- §bX: 923§r §bY: 4§r §bZ: -488§r §bD: 0§r -----
So it breaks.
Will fix it in next release.

**Comment by TimberDimber** [comment]
> So it breaks. Will fix it in next release.

So, he can use one (four) input hatch and then link it to Remote Inputs in other aals?

**Comment by reobf** [comment]
Yes

**Comment by reobf** [comment]
I now understand why they change colour code...
They use Strikethrough to connect hyphens
to eliminiate tiny spaces between characters.
 a -----
 a ~~-----~~
