### ISSUE TITLE
优先级过滤存储输入仓拉入不了东西

### ISSUE THREAD

**Issue by NNNNMMMMIIII** [reobf/Programmable-Hatches-Mod#89]
ME超级箱和ME超级缸无效，放进去都拉取不了，版本19P17 GTNH270 beta-3
![屏幕截图 2024-10-27 045835](https://github.com/user-attachments/assets/22c4ac18-d6a0-4fc9-a9fe-14ef04211334)
![屏幕截图 2024-10-27 045828](https://github.com/user-attachments/assets/b25541e3-fbd3-433d-9da0-86ff804a2f7e)
![屏幕截图 2024-10-27 045823](https://github.com/user-attachments/assets/813c0802-53ce-4d80-bcf8-c4232f7f3074)
![屏幕截图 2024-10-27 045815](https://github.com/user-attachments/assets/42f015a6-a05d-4862-b698-4f9543bf6b03)
![屏幕截图 2024-10-27 045756](https://github.com/user-attachments/assets/c7ee74c8-9487-48cd-8cf0-a87de1cd46b4)

**Comment by reobf** [comment]
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/0.0.19p18-beta
