### ISSUE TITLE
关于多方块编程器电路提供器的一些建议

### ISSUE THREAD

**Issue by Handsonzyx** [reobf/Programmable-Hatches-Mod#9]
看游戏内物品描述貌似目前计划的功能仅仅是省频道的作用（可能我理解有误），感觉可以buff一下，比如考虑支持输入总线？

**Comment by reobf** [comment]
主要是通过提供器访问仓，将一个网络中的编程器电路合成提供给多个子网

**Comment by Handsonzyx** [comment]
感觉子网需要下单的时候也不多，只是目前的功能的话感觉实用性还是不太大？

**Comment by Handsonzyx** [comment]
多方块提供器能不能把空白的那个虚拟电路默认集成进去，目前那些预构提供器好像都不提供空白的。

**Comment by reobf** [comment]
> 多方块提供器能不能把空白的那个虚拟电路默认集成进去，目前那些预构提供器好像都不提供空白的。

塞一个不放东西的的T0提供器就行了 大提供器能识别的
