### ISSUE TITLE
ae下单后崩溃，而后无法进入存档。

### ISSUE THREAD

**Issue by PinkYuDeer** [reobf/Programmable-Hatches-Mod#91]
版本：0.0.19p17 2.7.0 beta3
崩溃日志：
[crash-2024-10-28_20.23.18-server.txt](https://github.com/user-attachments/files/17542309/crash-2024-10-28_20.23.18-server.txt)

**Comment by reobf** [comment]
或许不是我的锅
https://github.com/GTNewHorizons/AE2FluidCraft-Rework/pull/233
这个PR似乎修复报错的那一行 或许就是你遇到的问题？
尝试[1.3.42-gtnh](https://github.com/GTNewHorizons/AE2FluidCraft-Rework/releases/tag/1.3.42-gtnh)或者更新的版本试试？你是1.3.41-gtnh

**Comment by PinkYuDeer** [comment]
神 你是我的神

**Comment by reobf** [comment]
![1730120871458](https://github.com/user-attachments/assets/0491ec63-49b1-42b2-b63c-9cd30936f625)
改动的地方
