### ISSUE TITLE
New Hatch? (again?)

### ISSUE THREAD

**Issue by TimberDimber** [reobf/Programmable-Hatches-Mod#92]
Again a few new ideas for hatch improvements (Evgengoldwar proposed), primarily for chemistry:
1) Void Hatch/Bus: where you can specify 1/4/16 types of fluids/items to void with priority settings. Currently, this can theoretically be achieved using a regular output hatch with a void cover. However, if there’s an AE output, it has priority and the regular output doesn't receive anything. Even when a specific output is selected in the hatch, it still directs items/fluids to the AE output.
2) Hatch/Bus with Built-In Level Emitter Mechanic: Similar to the existing restricted stocking, but with an integrated level emitter function. Instead of monitoring levels of items/fluids directly, this hatch would track levels based on the specified filter and activate/deactivate based on whether the levels fall below/rise above the set threshold.

**Comment by reobf** [comment]
1.
cannot reproduce 
ME Hatch/Bus is not prioritized, they have the same priority as normal one.
it depends on the order that the controller checks the structure.
ME Hatch/Bus with fluid/item locked has higher priority...
![2024-11-03_17 58 22](https://github.com/user-attachments/assets/d61ec7e1-b771-41f5-acea-669bfd4aa5ed)
![2024-11-03_17 58 27](https://github.com/user-attachments/assets/f9d0e752-521e-4b3d-a14c-166ed88273e4)

**Comment by reobf** [comment]
2.
Do you mean the level of fluid it should check is different from what it pulls?
You can use ME Emitter+Control Cover to do this.
You can trun off restricted stocking by mallet or Control Cover, in case you don't know.

**Comment by reobf** [comment]
I checked the code...
Hatch with mode "Outputs misc. Fluids, Steam and Items" is not regarded prioritized, even if you specify the fluid.

**Comment by evgengoldwar** [comment]
> I checked the code... Hatches with mode "Outputs misc. Fluids, Steam and Items"(default mode) is not regarded prioritized, even if you specify the fluid. You should use screwdriver to change it.

1) This is the addition of a new hatch for multiblocks and will have priority over the others in it you can specify the desired liquid or items and they will voided and everything that did not get into it will go to other hatch

**Comment by evgengoldwar** [comment]
> Do you mean the level of fluid it should check is different from what it pulls? You can use ME Emitter+Control Cover to do this. You can trun off restricted stocking by mallet or Control Cover(when off, it will pull nothing), in case you don't know.

2) It is a suggestion to add a hatch that will have emitter logic + cover only within the hatch so that no additional logic is built.

**Comment by reobf** [comment]
> > I checked the code... Hatches with mode "Outputs misc. Fluids, Steam and Items"(default mode) is not regarded prioritized, even if you specify the fluid. You should use screwdriver to change it.
> 
> 1. This is the addition of a new hatch for multiblocks and will have priority over the others in it you can specify the desired liquid or items and they will voided and everything that did not get into it will go to other hatch

I know, but I'm talking about 
> However, if there’s an AE output, it has priority and the regular output doesn't receive anything. Even when a specific output is selected in the hatch, it still directs items/fluids to the AE output.

not being true, at lest in 2.6.1

Anyway, okay, maybe in the next release.

**Comment by reobf** [comment]
> > Do you mean the level of fluid it should check is different from what it pulls? You can use ME Emitter+Control Cover to do this. You can trun off restricted stocking by mallet or Control Cover(when off, it will pull nothing), in case you don't know.
> 
> 2. It is a suggestion to add a hatch that will have emitter logic + cover only within the hatch so that no additional logic is built.

How about a new cover that intergrates  Control Cover+ ME Emitter(reads the ME storage of the ME hatch's network,requires no channel)?
Place it on restricted stocking,set filter config in its GUI,and it should do the job in one single block.

**Comment by evgengoldwar** [comment]
> > > Do you mean the level of fluid it should check is different from what it pulls? You can use ME Emitter+Control Cover to do this. You can trun off restricted stocking by mallet or Control Cover(when off, it will pull nothing), in case you don't know.
> > 
> > 
> > 
> > 2. It is a suggestion to add a hatch that will have emitter logic + cover only within the hatch so that no additional logic is built.
> 
> How about a new cover that intergrates Control Cover+ ME Emitter(reads the ME storage of the ME hatch's network,requires no channel)? Place it on restricted stocking,set filter config in its GUI,and it should do the job in one single block.

Yea

**Comment by evgengoldwar** [comment]
> > > I checked the code... Hatches with mode "Outputs misc. Fluids, Steam and Items"(default mode) is not regarded prioritized, even if you specify the fluid. You should use screwdriver to change it.
> > 
> > 
> > 
> > 1. This is the addition of a new hatch for multiblocks and will have priority over the others in it you can specify the desired liquid or items and they will voided and everything that did not get into it will go to other hatch
> 
> I know, but I'm talking about
> 
> > However, if there’s an AE output, it has priority and the regular output doesn't receive anything. Even when a specific output is selected in the hatch, it still directs items/fluids to the AE output.
> 
> not being true, at lest in 2.6.1
> 
> Anyway, okay, maybe in the next release.

I guess Void Hatch that shoold have priority over Ae and Simple Hatch if that's what you mean.

**Comment by reobf** [comment]
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/0.0.19p23-beta
without recipe though

**Comment by evgengoldwar** [comment]
> https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/0.0.19p23-beta without recipe though

Yeah, that's what's been missing. Thank you. Best developer ever.
