### ISSUE TITLE
存储代理器id问题

### ISSUE THREAD

**Issue by Koamasi** [reobf/Programmable-Hatches-Mod#93]
方块形式的存储代理器id相同导致物品在进入背包时会与现有的其他方块形式代理器堆叠

https://github.com/user-attachments/assets/41897578-cd02-4657-b97c-19db288ce6cc

**Comment by reobf** [comment]
感谢反馈 修了
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/0.0.19p19-beta
顺带一提这东西的功能 在270 被原版存储总线替代了
因为270存储总线的过滤可以同时做读&写过滤
之前只能写过滤
