### ISSUE TITLE
关于编程电路板（重置）

### ISSUE THREAD

**Issue by Cori885** [reobf/Programmable-Hatches-Mod#94]
270beta2版本，多方块编程电路提供器无法提供编程电路板（重置）

**Comment by reobf** [comment]
现在手头没电脑 
先问几个问题
1.关10秒在再开一次能解决吗
2.多方块提供器不会默认提供空电路 需要一个空的提供器(预构不提供空电路，满的t0/t1也不提供)，确定有吗
3.大提供上的小提供放东西能提供电路合成吗(不使用预购提供器)

**Comment by reobf** [comment]
如果都不能解决 等我手头有电脑....
顺带问一下java版本 mod版本

**Comment by Cori885** [comment]
我要回去试一下，因为我构建出来后没有放入空的提供器，直接放入满的

**Comment by reobf** [comment]
如果能在加了空提供器的情况下复现
再reopen吧 先关了
