### ISSUE TITLE
在下单合成过程中发生崩溃

### ISSUE THREAD

**Issue by Armelia-William** [reobf/Programmable-Hatches-Mod#96]
原因不明，崩溃后能进入游戏一会，在这段时间内把合成CPU断掉可以避免继续崩溃，否则加载完AE系统后继续崩溃
这个订单下单后崩溃可重复复现，稳定报错java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
但是因为是一个装配线组的全家桶自定义假配方，具体是哪个机器或者仓室的问题我还需要排查很久，暂时没找到问题所在
![image](https://github.com/user-attachments/assets/5d26cd3a-5b14-4ad5-ae04-d7a93de89dde)
[crash-2024-11-06_23.31.08-server.txt](https://github.com/user-attachments/files/17649684/crash-2024-11-06_23.31.08-server.txt)

**Comment by reobf** [comment]
我的问题 修了
样板影射镜像 访问对象 应该是远程的仓 写错成自身了
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/0.0.19p21-beta

**Comment by Armelia-William** [comment]
> 我的问题 修了 某个地方样板影射镜像 访问对象 应该是远程的仓 写错成自身了 https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/0.0.19p21-beta

OK，好像没问题了，之前PCB工厂用了镜像仓，所以合成湿件电路基板崩了。
