### ISSUE TITLE
装配线诱骗存储输入总线遇到一个非常诡异的BUG

### ISSUE THREAD

**Issue by Armelia-William** [reobf/Programmable-Hatches-Mod#98]
简单来说就是右键打开连入装配线诱骗存储输入总线会把整个世界的所有AE网络物品存储全部离线，不管有没有与之连接的AE网络，只有退出存档重进，才能恢复正常
但是合成没有问题，只要不打开GUI就行，单独放置的装配线诱骗存储输入仓在连入的打开没有问题，不会出现物品消失的情况
但只要连入网络，并且网络结构中有子网 也就是ME存储总线→ME接口的情况，就会出现以上离线问题
![image](https://github.com/user-attachments/assets/2618dd4c-9724-4464-bd89-413cd48bc669)
![2024-11-08_14 04 57](https://github.com/user-attachments/assets/83558ea5-7c0c-4345-b628-d8d3d847e7f8)
![2024-11-08_14 20 40](https://github.com/user-attachments/assets/cc495dba-a799-4b9d-950a-9ce045c68b6e)

**Comment by reobf** [comment]
试试这个 先顶着用吧 
[programmablehatches-0.0.19p22.zip](https://github.com/user-attachments/files/17674496/programmablehatches-0.0.19p22.zip)
改.jar后缀或者直接用 github不让传jar

**Comment by Armelia-William** [comment]
> 试试这个 先顶着用吧 [programmablehatches-0.0.19p22.zip](https://github.com/user-attachments/files/17674496/programmablehatches-0.0.19p22.zip) 改.jar后缀或者直接用 github不让传jar

OK，另外我没太看懂装配线诱骗存储输入总线的作用，诱骗输入总线改成普通的优先级拉取一样可以正常运作，
所以是给进装用不会吞物品，然后重复物品不用改名了吗？

**Comment by haliludaxuanfeng** [comment]
如果全用独立子网 做马达这种同物品在不同子网不改名的话就会先吃掉之前子网的物品 即使存储输入总线没和第一个子网连接 然后出现缺物品堵塞

**Comment by Armelia-William** [comment]
> 如果全用独立子网 做马达这种同物品在不同子网不改名的话就会先吃掉之前子网的物品 即使存储输入总线没和第一个子网连接 然后出现缺物品堵塞

这个我知道，所以说用第16个接口用用装配线诱骗输入总线后，重复物品不需要改名了？所有物品都从最后一个诱骗总线那里提取，他这个诱骗是这个意思吗？

**Comment by haliludaxuanfeng** [comment]
虽然我不知道是不是全从诱骗输入总线提取 但是使用后不用改名就可以解决这个问题（ ）

**Comment by reobf** [comment]
很难说官方是不是故意的，不过貌似看起来他们目前想维持装配线的现状

**Comment by reobf** [comment]
官方为了解决“两个me输入含有同种物品，到底按两份算还是一份算”的问题
直接一刀切按一份算，这对普通大机器时没问题的
但是装配线不是普通大机器，仅仅加了个每个总线第一格格子的检查
然后**强行假设** 你的所有me输入都共用一个网络，或者说**从哪个输入总线抽物品都一样**

所以要求
1.所有me输入总线第一格格子的物品类型正确，不检查数量
2.检查数量时从**最后一个出现该物品的me输入总线**检查数量并从那里抽物品（复用了普通大机器的物品搜寻逻辑，问题在这里）

**Comment by Armelia-William** [comment]
> 官方为了解决“两个me输入含有同种物品，到底按两份算还是一份算”的问题 直接一刀切按一份算，这对普通大机器时没问题的 但是装配线不是普通大机器，仅仅加了个每个总线第一格格子的检查 然后**强行假设** 你的所有me输入都共用一个网络，或者说**从哪个输入总线抽物品都一样**
> 
> 所以要求 1.所有me输入总线第一格格子的物品类型正确，不检查数量 2.检查数量时从**最后一个出现该物品的me输入总线**检查数量并从那里抽物品（复用了普通大机器的物品搜寻逻辑，问题在这里）
> 
> 诱骗总线总是能成为**最后一个出现xx物品的me输入总线**,并保证**第一格格子的物品类型正确（如果是16格配方）**，并保证**不会**抽干某个子网导致该子网**对应总线第一格为空**
> 
> 当然 也利用了装配线不会检测配方格子数以外格子的特性，比如4格配方，第五格放什么也不会影响配方检测（尽管如此，这只是检测类型时，计算数量和抽取时还是从**最后一个出现该物品的me输入总线**抽）

OK，我懂了）

**Comment by reobf** [comment]
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/0.0.19p23-beta

**Comment by PinkYuDeer** [comment]
> 官方为了解决“两个me输入含有同种物品，到底按两份算还是一份算”的问题 直接一刀切按一份算，这对普通大机器时没问题的 但是装配线不是普通大机器，仅仅加了个每个总线第一格格子的检查 然后**强行假设** 你的所有me输入都共用一个网络，或者说**从哪个输入总线抽物品都一样**
> 
> 所以要求 1.所有me输入总线第一格格子的物品类型正确，不检查数量 2.检查数量时从**最后一个出现该物品的me输入总线**检查数量并从那里抽物品（复用了普通大机器的物品搜寻逻辑，问题在这里）
> 
> 诱骗总线总是能成为**最后一个出现xx物品的me输入总线**,并保证**第一格格子的物品类型正确（如果是16格配方）**，并保证**不会**抽干某个子网导致该子网**对应总线第一格为空**
> 
> 当然 也利用了装配线不会检测配方格子数以外格子的特性，比如4格配方，第五格放什么也不会影响配方检测（尽管如此，这只是检测类型时，计算数量和抽取时还是从**最后一个出现该物品的me输入总线**抽）

非常好解释，没看懂tooltip但是这个看懂了

**Comment by PinkYuDeer** [comment]
如果按照优先级“4 3 2 1” 分别有 “板3 板3 板3 螺丝3”  
- 样板是“板1 板1 板1 螺丝1”的话，
使用诱骗输入总线抽取完成一次配方的结果
-    是  “板2 板2 板2 螺丝2” 
- 还是 “板3 板3   0   螺丝2”  捏？

**Comment by reobf** [comment]
> 如果按照优先级“4 3 2 1” 分别有 “板3 板3 板3 螺丝3”
> 
> * 样板是“板1 板1 板1 螺丝1”的话，
>   使用诱骗输入总线抽取完成一次配方的结果
> * 是  “板2 板2 板2 螺丝2”
> * 还是 “板3 板2 板1 螺丝2”  捏？
> * 还是 “板3 板3 板0 螺丝2”  捏？

板2 板2 板2 螺丝2

事实上你的优先级其实也不是很重要，能区分出16个不同的存储即可
只要保证最后一个子网的物品能出现在诱骗的第一格即可
