### ISSUE TITLE
关于ae样板优化

### ISSUE THREAD

**Issue by Cori885** [reobf/Programmable-Hatches-Mod#99]
有没有可能做到，我下单114514的锭，但是我样板是1出1，他发配就按114514出114514发配

**Comment by reobf** [comment]
你是否在找:并行单元
不考虑性能问题加并行就完事了
那几个可以塞样板的仓是有特殊优化的，在仓容量以及并行允许的情况下会尽量多发配，而且只需要计算一次 ，这个对服务器负载比较友好

**Comment by Weiyi122332** [comment]
> 你是否在找:并行单元 不考虑性能问题加并行就完事了 那几个可以塞样板的仓是有特殊优化的，在仓容量以及并行允许的情况下会尽量多发配，而且只需要计算一次 ，这个对服务器负载比较友好

后期我用下来实际的问题是ae计算的问题，而不是发配，发配最多掉tps。0-2分钟恢复正常，但是计算是真的慢，如果家里有被动产线，你就会发现算半天下不去单子，真的很难受
